---
title: "Untitled"
author: "Karina Roitman"
date: "2025-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
ciego_incorporado<-list(metrics_rf_equipo_ciego,
metrics_KNN_dic_equipo_ciego,
metrics_RANGER_equipo_ciego,
metrics_rf_fecha_ciego,
metrics_rf_matrix_ciego, metricsRF_matrix_carga_ciego, metricsKNN_equipo_dic_cc_ciego, metricsRanger_matrix_dich_cc_ciego
) %>%
  reduce(full_join, by = "Metric")
ciego_incorporado[, -1] <- round(ciego_incorporado[, -1], 3)
ciego_incorporado[is.na(ciego_incorporado)] <- 0
ciego_incorporado[] <- lapply(ciego_incorporado, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})
write.csv(ciego_incorporado, file = "resultados_ciego_incorporado.csv", row.names = FALSE)
```


```{r}
saveRDS(ciego_incorporado, "ciego_incorporado.rds")
```

```{r}

library(dplyr)
library(purrr)

# Todos de una vez
ML_tot_batch_no_dico_equipo <- list(metrics_rf_equipo, metrics_glm_equipo, metrics_KNN_equipo, metrics_RANGER_equipo) %>%
  reduce(full_join, by = "Metric")
ML_tot_batch_no_dico_equipo[, -1] <- round(ML_tot_batch_no_dico_equipo[, -1], 3)

ML_tot_batch_no_dico_equipo[is.na(ML_tot_batch_no_dico_equipo)] <- 0
ML_tot_batch_no_dico_equipo[] <- lapply(ML_tot_batch_no_dico_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})

print(ML_tot_batch_no_dico_equipo)

ML_tot_batch_no_dico_fecha <- list(metrics_rf_fecha,  metrics_glm_fecha, metrics_KNN_fecha,metrics_ranger_fecha) %>%
  reduce(full_join, by = "Metric")
ML_tot_batch_no_dico_fecha[, -1] <- round(ML_tot_batch_no_dico_fecha[, -1], 3)


ML_tot_batch_no_dico_fecha[] <- lapply(ML_tot_batch_no_dico_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})
print(ML_tot_batch_no_dico_fecha)
```


```{r}
ML_tot_batch_dico_equipo <- list(metrics_rfdico_equipo,
metrics_GLM_equipo_dic_equipo,
metrics_KNN_dic_equipo,
metrics_RANGER_dico_equipo
) %>%
  reduce(full_join, by = "Metric")
ML_tot_batch_dico_equipo[, -1] <- round(ML_tot_batch_dico_equipo[, -1], 3)
ML_tot_batch_dico_equipo[is.na(ML_tot_batch_dico_equipo)] <- 0
ML_tot_batch_dico_equipo[] <- lapply(ML_tot_batch_dico_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_tot_batch_dico_equipo)
```


```{r}
ML_tot_batch_dico_fecha <- list(
metrics_RF_fecha_dic,
metrics_GLM_fecha_dic,
metrics_KNN_fecha_dic,
metrics_ran_fecha_dic
) %>%
  reduce(full_join, by = "Metric")
ML_tot_batch_dico_fecha[, -1] <- round(ML_tot_batch_dico_fecha[, -1], 3)
ML_tot_batch_dico_fecha[is.na(ML_tot_batch_dico_fecha)] <- 0
ML_tot_batch_dico_fecha[] <- lapply(ML_tot_batch_dico_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_tot_batch_dico_fecha)
```

```{r}
saveRDS(ML_tot_batch_dico_equipo, "ML_tot_batch_dico_equipo.rds")
```

```{r}
saveRDS(ML_tot_batch_dico_fecha, "ML_tot_batch_dico_fecha.rds")
```

```{r}
saveRDS(ML_tot_batch_no_dico_equipo, "ML_tot_batch_no_dico_equipo.rds")
```

```{r}
saveRDS(ML_tot_batch_no_dico_fecha, "ML_tot_batch_no_dico_fecha.rds")
```

```{r}
# metrics_svm_matrix_dico_tot<-Results_Tot_Dic_ConLow_NoBatch[,c(1,3,4)]
# metrics_svm_matrix_dico_tot<-as.data.frame(metrics_svm_matrix_dico_tot)
# 
# library(dplyr)
# class(metrics_svm_matrix_tot)
# metrics_svm_matrix_tot <- metrics_svm_matrix_tot %>%
#   dplyr::rename(
#    SVMl_matrixdico_total= SVMl_D_To, 
#   SVMr_matrixdico_total= SVMr_D_To   # renombra equipo → equipo_id
#   )
```



```{r}
library(dplyr)

ML_tot_WObatch_dico <- list(metrics_rf_dico_matrix_tot,
metrics_GLM_dico_matrix_tot,
metrics_KNN_dico_matrix_tot,
metrics_RANGER_dico_matrix_dico
#metrics_svm_matrix_dico_tot
) %>%
  reduce(full_join, by = "Metric")
ML_tot_WObatch_dico[, -1] <- round(ML_tot_WObatch_dico[, -1], 3)
ML_tot_WObatch_dico[is.na(ML_tot_WObatch_dico)] <- 0
ML_tot_WObatch_dico[] <- lapply(ML_tot_WObatch_dico, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})

print(ML_tot_WObatch_dico)
```

```{r}
# 
# Results_Tot_Int_ConLow_NoBatch
# 
# 
# metrics_svm_matrix_tot<-Results_Tot_Int_ConLow_NoBatch[,c(1,3,4,5)]
# 
# library(dplyr)
# 
# metrics_svm_matrix_tot <- metrics_svm_matrix_tot %>%
#   rename(
#     SVMl_matrix_total = SVMl_I_To,     # renombra PCR.Cov → covid
#     SVMr_matrix_total = SVMr_I_To,
#     SVMpol_matrix_total = SVMp_I_To 
#   )
```




```{r}
ML_tot_WObatch <- list(
metrics_rf_sin_correccion,
metrics_GLM_matrix_total,
metrics_knn_matrix_total,
metrics_RANGER_matrix_tot
#metrics_svm_matrix_tot

) %>%
  reduce(full_join, by = "Metric")
ML_tot_WObatch[, -1] <- round(ML_tot_WObatch[, -1], 3)
ML_tot_WObatch[is.na(ML_tot_WObatch)] <- 0
ML_tot_WObatch[] <- lapply(ML_tot_WObatch, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_tot_WObatch)
```




```{r}
saveRDS(ML_tot_WObatch, "ML_tot_WObatch.rds")
```



```{r}
saveRDS(ML_tot_WObatch_dico, "ML_tot_WObatch_dico.rds")
```



```{r}
ML_high_batch_dico_equipo <- list(
metricsRF_equipo_dico_carga,
metricsGLM_equipo_dic_carga,
metrics_KNN_dic_equipo,
metricsRanger_equipo_dich_carga
) %>%
  reduce(full_join, by = "Metric")
ML_high_batch_dico_equipo[, -1] <- round(ML_high_batch_dico_equipo[, -1], 3)
ML_high_batch_dico_equipo[is.na(ML_high_batch_dico_equipo)] <- 0
ML_high_batch_dico_equipo[] <- lapply(ML_high_batch_dico_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})



print(ML_high_batch_dico_equipo)
```



```{r}
ML_high_batch_dico_fecha <- list(metricsRF_fecha_dic_carga,
metricsGLM_fecha_dic_carga,
metricsKNN_fecha_dic_carga,
metricsRANGER_fecha_dic_carga

) %>%
  reduce(full_join, by = "Metric")
ML_high_batch_dico_fecha[, -1] <- round(ML_high_batch_dico_fecha[, -1], 3)
ML_high_batch_dico_fecha[is.na(ML_high_batch_dico_fecha)] <- 0

ML_high_batch_dico_fecha[] <- lapply(ML_high_batch_dico_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_high_batch_dico_fecha)
```


```{r}
saveRDS(ML_high_batch_dico_equipo, "ML_high_batch_dico_equipo.rds")
```

```{r}
saveRDS(ML_high_batch_dico_fecha, "ML_high_batch_dico_fecha.rds")
```



```{r}
ML_high_batch_equipo <- list(
metricsRF_equipo_carga,
metricsGLM_equipo_carga,
metricsKNN_equipo_carga,

metricsRanger_equipo_carga
) %>%
  reduce(full_join, by = "Metric")
ML_high_batch_equipo[, -1] <- round(ML_high_batch_equipo[, -1], 3)
ML_high_batch_equipo[is.na(ML_high_batch_equipo)] <- 0
ML_high_batch_equipo[] <- lapply(ML_high_batch_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})



print(ML_high_batch_equipo)
```

```{r}
ML_high_batch_fecha <- list(metricsRF_fecha_carga,
metricsGLM_fecha_carga,
metricsRanger_FECHA_carga,

metricsKNN_fecha_carga



) %>%
  reduce(full_join, by = "Metric")
ML_high_batch_fecha[, -1] <- round(ML_high_batch_fecha[, -1], 3)
ML_high_batch_fecha[is.na(ML_high_batch_fecha)] <- 0
ML_high_batch_fecha[] <- lapply(ML_high_batch_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_high_batch_fecha)
```



```{r}
saveRDS(ML_high_batch_equipo, "ML_high_batch_equipo.rds")
```


```{r}
saveRDS(ML_high_batch_fecha, "ML_high_batch_fecha.rds")
```



```{r}
ML_high_WObatch <- list(
metricsRF_matrix_carga,
metricsGLM_matrix_carga,
metricsKNN_matrix_carga,
metricsRANGER_matrix_carga
) %>%
  reduce(full_join, by = "Metric")
ML_high_WObatch[, -1] <- round(ML_high_WObatch[, -1], 3)
ML_high_WObatch[is.na(ML_high_WObatch)] <- 0
ML_high_WObatch[] <- lapply(ML_high_WObatch, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})

print(ML_high_WObatch)
```

```{r}
saveRDS(ML_high_WObatch, "ML_high_WObatch.rds")
```


```{r}
ML_high_WObatch_dico <- list(
metricsRFd_carga, metricsGLMd_carga,
metricsKNNd_carga,
metricsRanger_matrix_dich_carga

) %>%
  reduce(full_join, by = "Metric")
ML_high_WObatch_dico[, -1] <- round(ML_high_WObatch_dico[, -1], 3)
ML_high_WObatch_dico[is.na(ML_high_WObatch_dico)] <- 0
ML_high_WObatch_dico[] <- lapply(ML_high_WObatch_dico, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_high_WObatch_dico)
```


```{r}
saveRDS(ML_high_WObatch_dico, "ML_high_WObatch_dico.rds")
```


```{r}
ML_covid_batch_fecha <- list(metrics_RF_fecha_covid,
                             metrics_GLM_fecha_covid, 
                             metrics_KNN_fecha_covid,
metrics_RANGER_fecha_covid



) %>%
  reduce(full_join, by = "Metric")
ML_covid_batch_fecha[, -1] <- round(ML_covid_batch_fecha[, -1], 3)
ML_covid_batch_fecha[is.na(ML_covid_batch_fecha)] <- 0
ML_covid_batch_fecha[] <- lapply(ML_covid_batch_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_covid_batch_fecha)
```


```{r}
ML_covid_batch_equipo <- list(
metrics_rf_equipo_covid,

metrics_GLM_covid_equipo,
metrics_KNN_equipo_covid,
metrics_RANGER_equipo_covid
) %>%
  reduce(full_join, by = "Metric")
ML_covid_batch_equipo[, -1] <- round(ML_covid_batch_equipo[, -1], 3)
ML_covid_batch_equipo[is.na(ML_covid_batch_equipo)] <- 0

ML_covid_batch_equipo[] <- lapply(ML_covid_batch_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})

print(ML_covid_batch_equipo)
```


```{r}
saveRDS(ML_covid_batch_equipo, "ML_covid_batch_equipo.rds")
```


```{r}
saveRDS(ML_covid_batch_fecha, "ML_covid_batch_fecha.rds")
```



```{r}
ML_covid_batch_dico_fecha <- list(metricsRF_fecha_dico_covid,
metricsGLM_fecha_dic_covid,
metrics_KNN_fecha_dic_covid,
metrics_Ranger_fecha_covid_dico

) %>%
  reduce(full_join, by = "Metric")
ML_covid_batch_dico_fecha[, -1] <- round(ML_covid_batch_dico_fecha[, -1], 3)
ML_covid_batch_dico_fecha[is.na(ML_covid_batch_dico_fecha)] <- 0

ML_covid_batch_dico_fecha[] <- lapply(ML_covid_batch_dico_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_covid_batch_dico_fecha)
```


```{r}
ML_covid_batch_dico_equipo <- list(
metrics_rf_dico_equipo,
metrics_GLM_dico_equipo_covid,
metrics_KNN_dico_equipo_covid,
metrics_ranger_equipo_dico_covid
) %>%
  reduce(full_join, by = "Metric")
ML_covid_batch_dico_equipo[, -1] <- round(ML_covid_batch_dico_equipo[, -1], 3)
ML_covid_batch_dico_equipo[is.na(ML_covid_batch_dico_equipo)] <- 0

ML_covid_batch_dico_equipo[] <- lapply(ML_covid_batch_dico_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_covid_batch_dico_equipo)
```


```{r}
saveRDS(ML_covid_batch_dico_equipo, "ML_covid_batch_dico_equipo.rds")
```


```{r}
saveRDS(ML_covid_batch_dico_fecha, "ML_covid_batch_dico_fecha.rds")
```

```{r}
ML_WObatch_covid_dico <- list(
metricsRFd_matrix_covid,
metricsGLMd_matrix_covid,
metricsKNNd_matrix_dico,

metricsRanger_matrix_dich_covid

) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_covid_dico[, -1] <- round(ML_WObatch_covid_dico[, -1], 3)
ML_WObatch_covid_dico[is.na(ML_WObatch_covid_dico)] <- 0


ML_WObatch_covid_dico[] <- lapply(ML_WObatch_covid_dico, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_WObatch_covid_dico)
```


```{r}
saveRDS(ML_WObatch_covid_dico, "ML_WObatch_covid_dico.rds")
```

```{r}
ML_WObatch_covid <- list(
metricsRF_fecha_covid,
metrics_GLM_fecha_covid,
metrics_KNN_fecha_covid,
metricsRanger_matrix_covid
) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_covid[, -1] <- round(ML_WObatch_covid[, -1], 3)
ML_WObatch_covid[is.na(ML_WObatch_covid)] <- 0

ML_WObatch_covid[] <- lapply(ML_WObatch_covid, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_WObatch_covid)
```

```{r}
saveRDS(ML_WObatch_covid, "ML_WObatch_covid.rds")
```


```{r}
ML_cc_batch_dico_equipo <- list(
metricsRF_equipo_dic_cc,
metricsGLM_equipo_dic_cc,
metricsKNN_equipo_dic_cc,
metricsRanger_equipo_dich_cc
) %>%
  reduce(full_join, by = "Metric")
ML_cc_batch_dico_equipo[, -1] <- round(ML_cc_batch_dico_equipo[, -1], 3)
ML_cc_batch_dico_equipo[is.na(ML_cc_batch_dico_equipo)] <- 0

ML_cc_batch_dico_equipo[] <- lapply(ML_cc_batch_dico_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})
print(ML_cc_batch_dico_equipo)
```


```{r}
ML_cc_batch_dico_fecha <- list(metricsRF_fecha_dic_cc,
metricsGLM_fecha_dic_cc,
metricsKNN_fecha_dic_cc,
metricsRanger_FECHA_dich_cc

) %>%
  reduce(full_join, by = "Metric")
ML_cc_batch_dico_fecha[, -1] <- round(ML_cc_batch_dico_fecha[, -1], 3)
ML_cc_batch_dico_fecha[is.na(ML_cc_batch_dico_fecha)] <- 0

ML_cc_batch_dico_fecha[] <- lapply(ML_cc_batch_dico_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_cc_batch_dico_fecha)
```


```{r}
saveRDS(ML_cc_batch_dico_equipo, "ML_cc_batch_dico_equipo.rds")
```


```{r}
saveRDS(ML_cc_batch_dico_fecha, "ML_cc_batch_dico_fecha.rds")
```

```{r}
ML_cc_batch_equipo <- list(
metricsRF_equipo_cc,

metricsGLM_equipo_cc,
metricsKNN_equipo_cc,
metricsRanger_equipo_cc
) %>%
  reduce(full_join, by = "Metric")
ML_cc_batch_equipo[, -1] <- round(ML_cc_batch_equipo[, -1], 3)
ML_cc_batch_equipo[is.na(ML_cc_batch_equipo)] <- 0

ML_cc_batch_equipo[] <- lapply(ML_cc_batch_equipo, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_cc_batch_equipo)
```


```{r}
ML_cc_batch_fecha <- list(metricsRF_fecha_cc,
                          metricsGLM_fecha_cc,
                          metricsKNN_fecha_cc,
metricsRanger_FECHA_cc

) %>%
  reduce(full_join, by = "Metric")
ML_cc_batch_fecha[, -1] <- round(ML_cc_batch_fecha[, -1], 3)
ML_cc_batch_fecha[is.na(ML_cc_batch_fecha)] <- 0

ML_cc_batch_fecha[] <- lapply(ML_cc_batch_fecha, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_cc_batch_fecha)
```


```{r}
saveRDS(ML_cc_batch_equipo, "ML_cc_batch_equipo.rds")
```

```{r}
saveRDS(ML_cc_batch_fecha, "ML_cc_batch_fecha.rds")
```


```{r}
ML_WObatch_cc_dico <- list(
metricsRFd_matrix_cc,
metricsGLMd_matrix_cc,
metricsKNNd_matrix_cc,
metricsRanger_matrix_dich_cc

  ) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_cc_dico[, -1] <- round(ML_WObatch_cc_dico[, -1], 3)
ML_WObatch_cc_dico[is.na(ML_WObatch_cc_dico)] <- 0

ML_WObatch_cc_dico[] <- lapply(ML_WObatch_cc_dico, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_WObatch_cc_dico)
```



```{r}
saveRDS(ML_WObatch_cc_dico, "ML_WObatch_cc_dico.rds")
```


```{r}
ML_WObatch_cc <- list(
metricsRF_matrix_cc,
metricsGLM_matrix_cc,
metricsKNN_MATRIX_cc,
metricsRANGER_matrix_cc

  ) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_cc[, -1] <- round(ML_WObatch_cc[, -1], 3)
ML_WObatch_cc[is.na(ML_WObatch_cc)] <- 0

ML_WObatch_cc[] <- lapply(ML_WObatch_cc, function(col) {
  if (is.numeric(col)) {
    redondeado <- round(col, 3)
    redondeado[redondeado == 0] <- "0"  # lo deja como 0 sin decimales
    return(redondeado)
  } else {
    return(col)
  }
})


print(ML_WObatch_cc)
```



```{r}
saveRDS(ML_WObatch_cc, "ML_WObatch_cc.rds")
```


```{r}

full<-list(ML_tot_batch_no_dico_equipo,ML_tot_batch_dico_fecha, ML_tot_WObatch_dico, ML_tot_WObatch, ML_high_batch_dico_equipo, ML_high_batch_fecha, ML_high_WObatch, ML_high_WObatch_dico, ML_covid_batch_equipo, ML_covid_batch_dico_fecha, ML_WObatch_covid_dico, ML_WObatch_covid, ML_cc_batch_dico_equipo, ML_cc_batch_fecha, ML_WObatch_cc_dico, ML_WObatch_cc
  ) %>%
  reduce(full_join, by = "Metric")



write.csv(full, file = "resultados_modelos.csv", row.names = FALSE)

```




```{r}
saveRDS(full, "full.rds")

```

```{r}
# 
ciegos<-list(metrics_RANGER_equipo_ciego, metrics_KNN_dic_equipo_ciego, metrics_rf_matrix_ciego, metrics_rf_equipo_ciego, metrics_rf_fecha_ciego, metricsRanger_matrix_dich_cc_ciego,metricsKNN_equipo_dic_cc_ciego, metricsRF_matrix_carga_ciego) %>%
  reduce(full_join, by = "Metric")

write.csv(full, file = "resultados_solo_ciego.csv", row.names = FALSE)
```



```{r}
rf_dico<-as.data.frame(c(metrics_rfdico_equipo, metrics_rf_dico_matrix_tot, metrics_RF_fecha_dic,  metricsRF_equipo_dico_carga, metricsRFd_carga, metricsRF_fecha_dic_carga, metrics_rf_equipo_covid, metrics_RF_fecha_covid, metricsRFd_matrix_covid, metricsRF_equipo_dic_cc, metricsRFd_matrix_cc,metricsRF_fecha_dic_cc))
```


```{r}
rf_nodico<-as.data.frame(c(metrics_rf_equipo,  metrics_rf_sin_correccion, metricsRF_equipo_carga, metricsRF_matrix_carga, metrics_rf_equipo_covid, metricsRF_fecha_covid,metricsRF_equipo_cc, metricsRF_matrix_cc, metrics_rf_fecha, metricsRF_fecha_carga, metrics_RF_fecha_covid, metricsRF_fecha_cc))
```

```{r}
glm_dico<- as.data.frame(c(metrics_GLM_equipo_dic_equipo, metrics_GLM_fecha_dic, metrics_GLM_dico_matrix_tot, metricsGLM_equipo_dic_carga, metricsGLMd_carga, metricsRF_fecha_dic_carga,metrics_GLM_dico_equipo_covid, metricsGLMd_matrix_covid, metricsGLM_fecha_dic_covid, metricsGLM_equipo_dic_cc, metricsGLM_fecha_dic_cc, metricsGLMd_matrix_cc))
```

```{r}
glm_nodico<-as.data.frame(c( metrics_glm_equipo, metrics_GLM_matrix_total, metricsGLM_equipo_carga, metricsGLM_matrix_carga, metrics_GLM_covid_equipo, metrics_GLM_fecha_covid, metricsGLM_equipo_cc, metricsGLM_matrix_cc, metricsGLM_fecha_cc , metricsGLM_fecha_dic_covid, metricsGLM_fecha_carga, metrics_glm_fecha ))
```

```{r}
KNN_dico<-list(metrics_KNN_dic_equipo, metrics_KNN_fecha_dic, metrics_KNN_dico_matrix_tot,  metrics_KNN_dico_equipo_covid, metrics_KNN_fecha_dic_covid,  metricsKNNd_matrix_dico,  metricsKNN_equipo_dic_cc, metricsKNN_fecha_dic_carga, metricsKNNd_carga, metricsKNN_equipo_dic_cc, metricsKNN_fecha_dic_cc,  metricsKNNd_matrix_cc) %>%
  reduce(full_join, by = "Metric")
  
```

```{r}
KNN_nodico<-list(metrics_KNN_equipo,  metrics_KNN_fecha, metrics_knn_matrix_total, metrics_KNN_equipo_covid, metrics_KNN_fecha_covid, metrics_KNN_fecha_covid,  metricsKNN_equipo_carga , metricsKNN_fecha_carga, metricsKNN_matrix_carga, metricsKNN_equipo_cc, metricsKNN_fecha_cc, metricsKNN_MATRIX_cc)%>%
  reduce(full_join, by = "Metric") 
```

```{r}
RANGER_dico<-list(metrics_RANGER_dico_equipo, metrics_ran_fecha_dic, metrics_RANGER_dico_matrix_dico,  metrics_ranger_equipo_dico_covid, metrics_Ranger_fecha_covid_dico, metricsRanger_matrix_dich_covid, metricsRanger_equipo_dich_carga, metricsRANGER_fecha_dic_carga, metricsRanger_matrix_dich_carga, metricsRanger_equipo_dich_cc, metricsRanger_FECHA_dich_cc, metricsRanger_matrix_dich_cc)%>%
  reduce(full_join, by = "Metric")
```


```{r}

RANGER_nodico<-list(metrics_RANGER_equipo, metrics_ranger_fecha, metrics_RANGER_matrix_tot, metrics_RANGER_equipo_covid, metrics_RANGER_fecha_covid,  metricsRanger_matrix_covid,  metricsRanger_equipo_carga, metricsRanger_FECHA_carga, metricsRANGER_matrix_carga, metricsRanger_equipo_cc, metricsRanger_FECHA_cc, metricsRANGER_matrix_cc)%>%
  reduce(full_join, by = "Metric")

```


```{r}
library(dplyr)
library(tidyverse)
class(rf_dico)


rf_dico <- rf_dico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))


rf_nodico_clean <- rf_nodico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))  # borra todas las columnas Metric.1, Metric.2, etc.

rf_dico_long <- rf_dico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))  

glm_dico_long <- glm_dico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))  

glm_nodico_long <- glm_nodico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))



library(tidyverse)

# Función para limpiar y convertir a largo
preparar_df <- function(df, algoritmo, tipo) {
  df %>%
    pivot_longer(-Metric, names_to = "modelo", values_to = "value") %>%
    mutate(Algorithm = algoritmo, Tipo = tipo)
}

# Aplicar a cada dataframe
rf_dico_long <- preparar_df(rf_dico_long, "RF", "dico")
rf_nodico_long <- preparar_df(rf_nodico_clean, "RF", "Intensidad")
glm_dico_long <- preparar_df(glm_dico_long, "GLM", "dico")
glm_nodico_long <- preparar_df(glm_nodico_long, "GLM", "Intensidad")
KNN_dico<- preparar_df(KNN_dico, "KNN", "dico")
KNN_nodico<- preparar_df(KNN_nodico, "KNN", "Intensidad")
RANGER_dico<- preparar_df(RANGER_dico, "RANGER", "dico")
RANGER_nodico<- preparar_df(RANGER_nodico, "RANGER", "Intensidad")

# Unir todos
df_plot <- bind_rows(rf_dico_long, rf_nodico_long, glm_dico_long, glm_nodico_long, KNN_dico, KNN_nodico, RANGER_dico, RANGER_nodico)
df_plot_filtrado <- df_plot %>%
  filter(Metric %in% c("Accuracy", "Kappa", "Sensitivity", "Specificity", "AUC"))

# Graficar
grafico_prueba<-ggplot(df_plot_filtrado, aes(x = Algorithm, y = value, color = Tipo)) +
  geom_point(position = position_jitter(width = 0.15), alpha = 0.8, size = 2) +
  facet_wrap(~ Metric, scales = "free_y") +
  theme_minimal() +
  labs(
    title = "Performance de las metricas por algoritmo y dicotomizacion",
    subtitle = "dico = binarized, no_dico = original intensities",
    x = "Algorithm",
    y = "Value",
    color = "Tipo de dato"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(face = "bold")
  )

save(grafico_prueba, file = "grafico_prueba.rda")
```


```{r}
save(grafico_prueba, file = "grafico_prueba.rda")
```


```{r}
library(plotly)
library(htmlwidgets)

# Usando tu objeto grafico_prueba
grafico_prueba_plotly <- ggplotly(
  grafico_prueba,
  tooltip = c("Metric", "Algorithm", "Tipo", "value")
)

grafico_prueba_plotly  # para verlo en RStudio/Viewer

# Guardar como HTML interactivo
saveWidget(as_widget(grafico_prueba_plotly), "grafico_prueba_interactivo.html", selfcontained = TRUE)
```


```{r}
save(grafico_prueba_plotly, file = "grafico_prueba_plotly.rda")
```


```{r}
library(dplyr)
library(ggplot2)
library(plotly)
library(scales)

df_plot_filtrado <- df_plot_filtrado %>%
  mutate(value_lbl = number(value, accuracy = 0.01))  # redondeo p/tooltip

grafico_prueba <- ggplot(
  df_plot_filtrado,
  aes(x = Algorithm, y = value, color = Tipo, shape = Tipo,
      text = paste0(
        "Metric: ", Metric,
        "<br>Algorithm: ", Algorithm,
        "<br>Tipo: ", Tipo,
        "<br>Value: ", value_lbl
      ))
) +
  geom_point(
    position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.6),
    alpha = 0.85, size = 2
  ) +
  facet_wrap(~ Metric, scales = "free_y") +
  theme_minimal() +
  labs(title = "Performance de las métricas por algoritmo y dicotomización",
       subtitle = "dico = binarized, no_dico = original intensities",
       x = "Algorithm", y = "Value", color = "Tipo de dato") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(face = "bold"))

grafico_prueba_plotly_2 <- ggplotly(grafico_prueba, tooltip = "text")
grafico_prueba_plotly_2
```




```{r}
names(rf_dico)
str(rf_dico)

```


```{r}
saveRDS(rf_dico, "rf_dico.rds")
saveRDS(rf_nodico, "rf_nodico.rds")
saveRDS(glm_dico, "glm_dico.rds")
saveRDS(glm_nodico, "glm_nodico.rds")
saveRDS(glm_nodico, "df_plot_filtrado.rds")

```

