---
title: "Untitled"
author: "Karina Roitman"
date: "2025-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
setwd("C:/Users/karin/Desktop/MCD/TESIS")
```

# 2. Cargar datos

```{r}
load("./Data_Kari/ciego/Average_ciego.Costa.Rica.4.rda")
load("./Data_Kari/ciego/Average_ciego.Costa.Rica.5.rda")
load("./Data_Kari/ciego/Average_ciego.Costa.Rica.6.rda")
load("./Data_Kari/ciego/Average_ciego.Malbran.4.rda")
```

CR4

```{r}
# Listado de tus dataframes
dataframes <- list(CostaRica.4.1.1)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$institucion <- "CR"
  df$equipo <- "CR"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales

CostaRica.4.1.1 <- dataframes[[1]]
```



```{r}
CostaRica.4.1.1<-CostaRica.4.1.1[,c(1,3,5,6,8,9)]
CostaRica.4.1.1<-data.frame(purrr::map(CostaRica.4.1.1, as.character ),
                               stringsAsFactors = FALSE)
```

```{r}

library(dplyr)

CostaRica.4.1.1 <- CostaRica.4.1.1 %>% rename(PCR.Cov = Virus)
CostaRica.4.1.1 <- CostaRica.4.1.1 %>% rename(fecha = protocolo)
library(dplyr)

CostaRica.4.1.1 <- CostaRica.4.1.1 %>% dplyr::select(spot.a.1, Carga, PCR.Cov, fecha, institucion, equipo)

```


CR5


```{r}
# Listado de tus dataframes
dataframes <- list(CostaRica.5.1)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$institucion <- "CR"
  df$equipo <- "CR"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales

CostaRica.5.1 <- dataframes[[1]]
```



```{r}
CostaRica.5.1<-CostaRica.5.1[,c(1,3,5,6,8,9)]
CostaRica.5.1<-data.frame(purrr::map(CostaRica.5.1, as.character ),
                               stringsAsFactors = FALSE)
```

```{r}

library(dplyr)

CostaRica.5.1 <- CostaRica.5.1 %>% rename(PCR.Cov = Virus)
CostaRica.5.1 <- CostaRica.5.1 %>% rename(fecha = protocolo)
library(dplyr)

CostaRica.5.1 <- CostaRica.5.1 %>% dplyr::select(spot.a.1, Carga, PCR.Cov, fecha, institucion, equipo)

```



CR6


```{r}
# Listado de tus dataframes
dataframes <- list(CostaRica.6.1)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$institucion <- "CR"
  df$equipo <- "CR"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales

CostaRica.6.1 <- dataframes[[1]]
```


```{r}
CostaRica.6.1<-CostaRica.6.1[,c(1,3,5,6,8,9)]
CostaRica.6.1<-data.frame(purrr::map(CostaRica.6.1, as.character ),
                               stringsAsFactors = FALSE)
```

```{r}

library(dplyr)

CostaRica.6.1 <- CostaRica.6.1 %>% rename(PCR.Cov = Virus)
CostaRica.6.1 <- CostaRica.6.1 %>% rename(fecha = protocolo)
library(dplyr)

CostaRica.6.1 <- CostaRica.6.1 %>% dplyr::select(spot.a.1, Carga, PCR.Cov, fecha, institucion, equipo)

```


MALBRAN 4

```{r}
# Listado de tus dataframes
dataframes <- list(Malbran_5_6.1)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$institucion <- "CR"
  df$equipo <- "CR"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales

Malbran_5_6.1 <- dataframes[[1]]
```



```{r}
Malbran_5_6.1<-Malbran_5_6.1[,c(1,3,5,6,8,9)]
Malbran_5_6.1<-data.frame(purrr::map(Malbran_5_6.1, as.character ),
                               stringsAsFactors = FALSE)
```


```{r}
Espec.ciego <- c(Espectros.CR4, Espectros.CR5, Espectros.CR6, Espectros.Malb.5_6)
                            

#Espectra.ciego <- alignSpectra(Espec.ciego, halfWindowSize=50, SNR=3, 
#                    tolerance=0.5, warpingMethod="quadratic")
```


```{r}
Espectra.ciego <- alignSpectra(
  Espec.ciego,
  halfWindowSize = 50,
  SNR = 3,
  tolerance = 0.8,
  warpingMethod = "quadratic",
  minFrequency = 0.2
)

```

