---
title: "Train_test_juntos"
author: "Karina Roitman"
date: "2024-09-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


Objetivos
=======================================================================

1. Cargar librerias. 
=======================================================================

rmarkdown como estrategia sintáctica. (En bibliografia hay 2 archivos)

```{r}
library(rmarkdown)
```

```{r}

library(stringr)
?stringr
library(tidyr)
?tidyr
library(dplyr)
library(openxlsx)
library(purrr)
library(broom)
library(ggplot2)
```

2. Cargar datos
=======================================================================

```{r}
library(MALDIquant)
?MALDIquant
library(MALDIquantForeign)
?MALDIquantForeign
```


```{r}
getwd()  # Verifica el directorio de trabajo actual

```

```{r}
setwd("C:/Users/karin/Desktop/MCD/TESIS")
```



```{r}
load("./Data_Kari/EspectrosINB/Average_ciego.INBIRS.1.rda")
load("./Data_Kari/EspectrosINB/Average_ciego.INBIRS.2.rda")
load("./Data_Kari/EspectrosINB/Average_ciego.INBIRS.3.rda")
load("./Data_Kari/EspectrosINB/Average_ciego.INBIRS.4.rda")
load("./Data_Kari/EspectrosHC/Average_HC_1.rda")
load("./Data_Kari/EspectrosHC/Average_HC_2.rda")
```


ACLARACION: EL ARCHIVO Average_HC_2.rda 

TODOS LOS 
Asigno batch, institucion y equipo
```{r}
# Listado de tus dataframes
dataframes <- list(Train.INB.1, Test.INB.1, INBIRS.1.df.f.1)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$fecha <- "16_7"
  df$institucion <- "inbirs"
  df$equipo <- "HC"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales
Train.INB.1<- dataframes[[1]]
Test.INB.1 <- dataframes[[2]]
INBIRS.1.df.f.1 <- dataframes[[3]]
```


```{r}
# Listado de tus dataframes
dataframes <- list(Train.INB.2, Test.INB.2, INBIRS.df.2.f)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$fecha <- "17_7"
  df$institucion <- "inbirs"
  df$equipo <- "HC"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales
Train.INB.2<- dataframes[[1]]
Test.INB.2 <- dataframes[[2]]
INBIRS.df.2.f <- dataframes[[3]]
```


```{r}
# Listado de tus dataframes
dataframes <- list(Train.INB.3, Test.INB.3, INBIRS.df.3.f)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$fecha <- "13_8"
  df$institucion <- "inbirs"
  df$equipo <- "HC"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales
Train.INB.3<- dataframes[[1]]
Test.INB.3 <- dataframes[[2]]
INBIRS.df.3.f <- dataframes[[3]]
```

```{r}
# Listado de tus dataframes
dataframes <- list(Train.INB.4, Test.INB.4, Espectros.INBIRS.4.f)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$fecha <- "18_8"
  df$institucion <- "inbirs"
  df$equipo <- "HC"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales
Train.INB.4<- dataframes[[1]]
Test.INB.4 <- dataframes[[2]]
Espectros.INBIRS.4.f<-dataframes[[3]]

```


```{r}
# Listado de tus dataframes
dataframes <- list(Categ.Hospi.1.Neg, Categ.Hospi.1.Pos, Categ.Hospi.2.Cnt, Categ.Hospi.2.Neg, Categ.Hospi.2.No.Covid, Categ.Hospi.2.Pos, Categ.Hospi.3.Neg, Categ.Hospi.3.No.Covid, Categ.Hospi.3.Pos)

# Usas lapply para agregar las columnas a cada dataframe
dataframes <- lapply(dataframes, function(df) {
  df$fecha <- "dia1"
  df$institucion <- "HdC"
  df$equipo <- "HC"
  return(df)
})

# Asignas los dataframes modificados de vuelta a sus nombres originales

Categ.Hospi.1.Neg<- dataframes[[1]]
Categ.Hospi.1.Pos<- dataframes[[2]]
Categ.Hospi.2.Cnt<- dataframes[[3]]
Categ.Hospi.2.Neg<- dataframes[[4]]
Categ.Hospi.2.No.Covid<- dataframes[[5]]
Categ.Hospi.2.Pos<- dataframes[[6]]
Categ.Hospi.3.Neg<- dataframes[[7]]
Categ.Hospi.3.No.Covid<- dataframes[[8]]
Categ.Hospi.3.Pos<- dataframes[[9]]

```



```{r , message=FALSE, echo=FALSE, warning=FALSE, out.width="100%"}

Espec.Union.Clin.Pos.Neg <- c(
                            Spectra.Train.INB.1,
                            Spectra.Test.INB.1,
                            Spectra.Train.INB.2,
                            Spectra.Test.INB.2,
                            Spectra.Train.INB.3,
                            Spectra.Test.INB.3,
                            Spectra.Train.INB.4,
                            Spectra.Test.INB.4,
                            Espectros.HC.1.Neg,
                            Espectros.HC.1.HighPos,
                            Espectros.HC.2.Cnt,
                            Espectros.HC.2.Neg,
                            Espectros.HC.2.No.covid,
                            Espectros.HC.2.IntPos,
                            Espectros.HC.3.Neg,
                            Espectros.HC.3.No.covid,
                            Espectros.HC.3.LowPos
                            )

Espectra.1 <- alignSpectra(Espec.Union.Clin.Pos.Neg, halfWindowSize=50, SNR=3, 
                    tolerance=0.5, warpingMethod="quadratic")
```




```{r}
inbirsTRAIN1<-Train.INB.1[,c(1:3,5:10)]
inbirsTRAIN1<-data.frame(map(inbirsTRAIN1, as.character),
                               stringsAsFactors = FALSE)
  
inbirsTEST1<- Test.INB.1[,c(1:3,5:10)]
inbirsTEST1<-data.frame(map(inbirsTEST1, as.character),
                               stringsAsFactors = FALSE)

inbirsTRAIN2<-Train.INB.2[,c(1:3,5:10)]
inbirsTRAIN2<-data.frame(map(inbirsTRAIN2, as.character),
                               stringsAsFactors = FALSE)
  
inbirsTEST2<- Test.INB.2[,c(1:3,5:10)]
inbirsTEST2<-data.frame(map(inbirsTEST2, as.character),
                               stringsAsFactors = FALSE)

inbirsTRAIN3<-Train.INB.3[,c(1:3,5:10)]
inbirsTRAIN3<-data.frame(map(inbirsTRAIN3, as.character),
                               stringsAsFactors = FALSE)
  
inbirsTEST3<- Test.INB.3[,c(1:3,5:10)]
inbirsTEST3<-data.frame(map(inbirsTEST3, as.character),
                               stringsAsFactors = FALSE)

inbirsTRAIN4<-Train.INB.4[,c(1:3,5:10)]
inbirsTRAIN4<-data.frame(map(inbirsTRAIN4, as.character),
                               stringsAsFactors = FALSE)
  
inbirsTEST4<- Test.INB.4[,c(1:3,5:10)]
inbirsTEST4<-data.frame(map(inbirsTEST4, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.1.Neg<- Categ.Hospi.1.Neg[,c(1:5,7,10:12)]
Categ.Hospi.1.Neg<- data.frame(map(Categ.Hospi.1.Neg, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.1.Pos<- Categ.Hospi.1.Pos[,c(1:5,7,10:12)]
Categ.Hospi.1.Pos<-data.frame(map(Categ.Hospi.1.Pos, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.2.Cnt<- Categ.Hospi.2.Cnt[,c(1:5,8,11:13)]
Categ.Hospi.2.Cnt<-data.frame(map(Categ.Hospi.2.Cnt, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.2.Neg<- Categ.Hospi.2.Neg[,c(1:5,8,11:13)]
Categ.Hospi.2.Neg<-data.frame(map(Categ.Hospi.2.Neg, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.2.No.Covid<- Categ.Hospi.2.No.Covid[,c(1:5,8,11:13)]
Categ.Hospi.2.No.Covid<-data.frame(map(Categ.Hospi.2.No.Covid, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.2.Pos<- Categ.Hospi.2.Pos[,c(1:5,8,11:13)]
Categ.Hospi.2.Pos<-data.frame(map(Categ.Hospi.2.Pos, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.3.Neg<- Categ.Hospi.3.Neg[,c(1:5,8,11:13)]
Categ.Hospi.3.Neg<-data.frame(map(Categ.Hospi.3.Neg, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.3.No.Covid<- Categ.Hospi.3.No.Covid[,c(1:5,8,11:13)]
Categ.Hospi.3.No.Covid<-data.frame(map(Categ.Hospi.3.No.Covid, as.character),
                               stringsAsFactors = FALSE)

Categ.Hospi.3.Pos<- Categ.Hospi.3.Pos[,c(1:5,8,11:13)]
Categ.Hospi.3.Pos<-data.frame(map(Categ.Hospi.3.Pos, as.character),
                               stringsAsFactors = FALSE)

```


```{r}
Base.Union.Clinc.Covid <- inbirsTRAIN1 %>%
  bind_rows(inbirsTEST1) %>%
  bind_rows(inbirsTRAIN2) %>%
  bind_rows(inbirsTEST2) %>%
  bind_rows(inbirsTRAIN3) %>%
  bind_rows(inbirsTEST3)%>%
  bind_rows(inbirsTRAIN4) %>%
  bind_rows(inbirsTEST4)%>%
bind_rows(Categ.Hospi.1.Neg)%>%
bind_rows(Categ.Hospi.1.Pos)%>%
bind_rows(Categ.Hospi.2.Cnt)%>%
bind_rows(Categ.Hospi.2.Neg)%>%
bind_rows(Categ.Hospi.2.No.Covid)%>%
bind_rows(Categ.Hospi.2.Pos)%>%
bind_rows(Categ.Hospi.3.Neg)%>%
bind_rows(Categ.Hospi.3.No.Covid)%>%
bind_rows(Categ.Hospi.3.Pos)

```

```{r}
Espectra.Orig <- data.frame(names(Espectra.1),
                                  stringsAsFactors = FALSE)
names(Espectra.Orig)<- c("spot.a.1")

Datos_actualizados<-  Espectra.Orig %>%
  left_join( Base.Union.Clinc.Covid, by="spot.a.1")
```

```{r}
dev.new()

# Inicializar el gráfico con el primer espectro
plot(Espectra.1[[1]], main = "Espectros Superpuestos", col = "blue", type = "l")

# Iterar sobre los espectros restantes y agregarlos al gráfico
for (i in 2:length(Espectra.1)) {
  lines(Espectra.1[[i]], col = i)  # Añadir líneas para cada espectro, con diferentes colores
}

# Añadir una leyenda para indicar los colores de cada espectro
legend("topright", legend = 1:length(Espectra.1), col = 1:length(Espectra.1),
       title = "Espectros", cex = 0.8)
```



```{r , message=FALSE, echo=FALSE, warning=FALSE}

peaks <- detectPeaks(Espectra.1, SNR = 3, 
                     method="MAD", halfWindowSize=50)
peaks <- binPeaks(peaks,tolerance=0.5)

species.Ave<-factor(Datos_actualizados$PCR.Cov) 
spot.factor.Avera<-factor(Datos_actualizados$spot.a.1) 

peaks <- filterPeaks(peaks, minFrequency=c(0.33, 0.33),
                     labels = species.Ave,
                     mergeWhitelists=TRUE)

featureMatrix <- intensityMatrix(peaks, Espectra.1)
```


```{r}
featureMatrix<- cbind(featureMatrix, label=Datos_actualizados$spot.a.1, covid=Datos_actualizados$PCR.Cov, carga=Datos_actualizados$Carga, dia=Datos_actualizados$batch, equipo=Datos_actualizados$equipo, fecha=Datos_actualizados$fecha, institucion=Datos_actualizados$institucion)
```




