---
title: "Untitled"
author: "Karina Roitman"
date: "2025-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(dplyr)

# Todos de una vez
ML_tot_batch_no_dico <- list(metrics_rf_equipo, metrics_KNN_equipo, metrics_glm_equipo, metrics_RANGER_equipo, metrics_rf_fecha, metrics_KNN_fecha, metrics_glm_fecha, metrics_ranger_fecha) %>%
  reduce(full_join, by = "Metric")
ML_tot_batch_no_dico[, -1] <- round(ML_tot_batch_no_dico[, -1], 3)
print(ML_tot_batch_no_dico)
```


```{r}
ML_tot_batch_dico <- list(metrics_rfdico_equipo,
metrics_GLM_equipo_dic_equipo,
metrics_KNN_dic_equipo,
metrics_RANGER_dico_equipo,
metrics_RF_fecha_dic,
metrics_GLM_fecha_dic,
metrics_ran_fecha_dic,
metrics_KNN_fecha_dic
) %>%
  reduce(full_join, by = "Metric")
ML_tot_batch_dico[, -1] <- round(ML_tot_batch_dico[, -1], 3)
print(ML_tot_batch_dico)
```



```{r}
library(dplyr)

ML_tot_WObatch_dico <- list(metrics_rf_dico_matrix_tot,
metrics_KNN_dico_matrix_tot,
metrics_GLM_dico_matrix_tot,
metrics_RANGER_dico_matrix_dico
) %>%
  reduce(full_join, by = "Metric")
ML_tot_WObatch_dico[, -1] <- round(ML_tot_WObatch_dico[, -1], 3)
print(ML_tot_WObatch_dico)
```


```{r}
ML_tot_WObatch <- list(
metrics_rf_sin_correccion,
metrics_GLM_matrix_total,
metrics_knn_matrix_total,
metrics_RANGER_matrix_tot

) %>%
  reduce(full_join, by = "Metric")
ML_tot_WObatch[, -1] <- round(ML_tot_WObatch[, -1], 3)
print(ML_tot_WObatch)
```


```{r}
ML_high_batch_dico <- list(
metricsRF_equipo_dico_carga,
metricsGLM_equipo_dic_carga,
metricsKNN_equipo_dic,
metricsRanger_equipo_dich_carga,
metricsRANGER_fecha_dic_carga,
metricsRF_fecha_dic_carga,
metricsGLM_fecha_dic_carga,
metricsKNN_fecha_dic_carga

) %>%
  reduce(full_join, by = "Metric")
ML_high_batch_dico[, -1] <- round(ML_high_batch_dico[, -1], 3)
print(ML_high_batch_dico)
```



```{r}
ML_high_batch <- list(
metricsRF_equipo_carga,
metricsKNN_equipo_carga,
metricsGLM_equipo_carga,
metricsRanger_equipo_carga,
metricsRanger_FECHA_carga,
metricsRF_fecha_carga,
metricsKNN_fecha_carga,
metricsGLM_fecha_carga


) %>%
  reduce(full_join, by = "Metric")
ML_high_batch[, -1] <- round(ML_high_batch[, -1], 3)
print(ML_high_batch)
```




```{r}
ML_high_WObatch <- list(
metricsRF_matrix_carga,
metricsGLM_matrix_carga,
metricsKNN_matrix_carga,
metricsRANGER_matrix_carga


) %>%
  reduce(full_join, by = "Metric")
ML_high_WObatch[, -1] <- round(ML_high_WObatch[, -1], 3)
print(ML_high_WObatch)
```

```{r}
ML_high_WObatch_dico <- list(
metricsRFd_carga,
metricsKNNd_carga,
metricsGLMd_carga,
metricsRanger_matrix_dich_carga

) %>%
  reduce(full_join, by = "Metric")
ML_high_WObatch_dico[, -1] <- round(ML_high_WObatch_dico[, -1], 3)
print(ML_high_WObatch_dico)
```



```{r}
# ML_high_WObatch_dico <- list(
# metricsRFd_carga,
# metricsKNNd_carga,
# metricsGLMd_carga,
# metricsRanger_matrix_dich_carga
# 
# ) %>%
#   reduce(full_join, by = "Metric")
# ML_high_WObatch_dico[, -1] <- round(ML_high_WObatch_dico[, -1], 3)
# print(ML_high_WObatch_dico)
```

```{r}
ML_covid_batch <- list(
metrics_rf_equipo_covid,
metrics_KNN_equipo_covid,
metrics_GLM_covid_equipo,
metrics_RANGER_equipo_covid,
metrics_RANGER_fecha_covid,
metrics_RF_fecha_covid,
metrics_KNN_fecha_covid,
metrics_GLM_fecha_covid

) %>%
  reduce(full_join, by = "Metric")
ML_covid_batch[, -1] <- round(ML_covid_batch[, -1], 3)
print(ML_covid_batch)
```



```{r}
ML_covid_batch_dico <- list(
metrics_rf_dico_equipo,
metrics_GLM_dico_equipo_covid,
metrics_KNN_dico_equipo_covid,
metrics_ranger_equipo_dico_covid,
metrics_Ranger_fecha_covid_dico,
metricsRF_fecha_dico_covid,
metricsGLM_fecha_dic_covid,
metrics_KNN_fecha_dic_covid


) %>%
  reduce(full_join, by = "Metric")
ML_covid_batch_dico[, -1] <- round(ML_covid_batch_dico[, -1], 3)
print(ML_covid_batch_dico)
```

```{r}
ML_WObatch_covid_dico <- list(
metricsRFd_matrix_covid,
metricsKNNd_matrix_dico,
metricsGLMd_matrix_covid,
metricsRanger_matrix_dich_covid



) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_covid_dico[, -1] <- round(ML_WObatch_covid_dico[, -1], 3)
print(ML_WObatch_covid_dico)
```


```{r}
ML_WObatch_covid <- list(
metricsRF_fecha_covid,
metrics_GLM_fecha_covid,
metricsKNN_fecha_covid	,
metricsRanger_matrix_covid
) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_covid[, -1] <- round(ML_WObatch_covid[, -1], 3)
print(ML_WObatch_covid)
```

```{r}
ML_cc_batch_dico <- list(
metricsRF_equipo_dic_cc,
metricsGLM_equipo_dic_cc,
metricsKNN_equipo_dic_cc,
metricsRanger_equipo_dich_cc,
metricsRanger_FECHA_dich_cc,
metricsRF_fecha_dic_cc,
metricsGLM_fecha_dic_cc,
metricsKNN_fecha_dic_cc


) %>%
  reduce(full_join, by = "Metric")
ML_cc_batch_dico[, -1] <- round(ML_cc_batch_dico[, -1], 3)
print(ML_cc_batch_dico)
```



```{r}
ML_cc_batch <- list(
metricsRF_equipo_cc,
metricsKNN_equipo_cc,
metricsGLM_equipo_cc,
metricsRanger_equipo_cc,
metricsRanger_FECHA_cc,
metricsRF_fecha_cc,
metricsKNN_fecha_cc,
metricsGLM_fecha_cc


) %>%
  reduce(full_join, by = "Metric")
ML_cc_batch[, -1] <- round(ML_cc_batch[, -1], 3)
print(ML_cc_batch)
```






```{r}
ML_WObatch_cc_dico <- list(
metricsRFd_matrix_cc,
metricsKNNd_matrix_cc,
metricsGLMd_matrix_cc,
metricsRanger_matrix_dich_cc

  ) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_cc_dico[, -1] <- round(ML_WObatch_cc_dico[, -1], 3)
print(ML_WObatch_cc_dico)
```

```{r}
ML_WObatch_cc <- list(
metricsRF_matrix_cc,
metricsGLM_matrix_cc,
metricsKNN_MATRIX_cc,
metricsRANGER_matrix_cc

  ) %>%
  reduce(full_join, by = "Metric")
ML_WObatch_cc[, -1] <- round(ML_WObatch_cc[, -1], 3)
print(ML_WObatch_cc)
```

```{r}

full<-list(ML_tot_batch_no_dico,ML_tot_batch_dico, ML_tot_WObatch_dico, ML_tot_WObatch, ML_high_batch_dico, ML_high_batch, ML_high_WObatch, ML_high_WObatch_dico, ML_covid_batch, ML_covid_batch_dico, ML_WObatch_covid_dico, ML_WObatch_covid, ML_cc_batch_dico, ML_cc_batch, ML_WObatch_cc_dico, ML_WObatch_cc
  ) %>%
  reduce(full_join, by = "Metric")

write.csv(full, file = "resultados_modelos_con_ciego.csv", row.names = FALSE)

```

```{r}
ciegos<-as.data
```





```{r}
saveRDS(full, "full.rds")

```


```{r}
rf_dico<-as.data.frame(c(metrics_rfdico_equipo, metrics_rf_dico_matrix_tot, metrics_RF_fecha_dic,  metricsRF_equipo_dico_carga, metricsRFd_carga, metricsRF_fecha_dic_carga, metrics_rf_equipo_covid, metrics_RF_fecha_covid, metricsRFd_matrix_covid, metricsRF_equipo_dic_cc, metricsRFd_matrix_cc,metricsRF_fecha_dic_cc))
```


```{r}
rf_nodico<-as.data.frame(c(metrics_rf_equipo,  metrics_rf_sin_correccion, metricsRF_equipo_carga, metricsRF_matrix_carga, metrics_rf_equipo_covid, metricsRF_fecha_covid,metricsRF_equipo_cc, metricsRF_matrix_cc, metrics_rf_fecha, metricsRF_fecha_carga, metrics_RF_fecha_covid, metricsRF_fecha_cc))
```

```{r}
glm_dico<- as.data.frame(c(metrics_GLM_equipo_dic_equipo, metrics_GLM_fecha_dic, metrics_GLM_dico_matrix_tot, metricsGLM_equipo_dic_carga, metricsGLMd_carga, metricsRF_fecha_dic_carga,metrics_GLM_dico_equipo_covid, metricsGLMd_matrix_covid, metricsGLM_fecha_dic_covid, metricsGLM_equipo_dic_cc, metricsGLM_fecha_dic_cc, metricsGLMd_matrix_cc))
```

```{r}
glm_nodico<-as.data.frame(c( metrics_glm_equipo, metrics_GLM_matrix_total, metricsGLM_equipo_carga, metricsGLM_matrix_carga, metrics_GLM_covid_equipo, metrics_GLM_fecha_covid, metricsGLM_equipo_cc, metricsGLM_matrix_cc, metricsGLM_fecha_cc , metricsGLM_fecha_dic_covid, metricsGLM_fecha_carga, metrics_glm_fecha ))
```


```{r}
library(dplyr)
library(tidyverse)
class(rf_dico)


rf_dico <- rf_dico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))


rf_nodico_clean <- rf_nodico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))  # borra todas las columnas Metric.1, Metric.2, etc.

rf_dico_long <- rf_dico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))  

glm_dico_long <- glm_dico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))  

glm_nodico_long <- glm_nodico %>%
  dplyr::select(-matches("^Metric\\.[0-9]+$"))



library(tidyverse)

# Función para limpiar y convertir a largo
preparar_df <- function(df, algoritmo, tipo) {
  df %>%
    pivot_longer(-Metric, names_to = "modelo", values_to = "value") %>%
    mutate(Algorithm = algoritmo, Tipo = tipo)
}

# Aplicar a cada dataframe
rf_dico_long <- preparar_df(rf_dico_long, "RF", "dico")
rf_nodico_long <- preparar_df(rf_nodico_clean, "RF", "no_dico")
glm_dico_long <- preparar_df(glm_dico_long, "GLM", "dico")
glm_nodico_long <- preparar_df(glm_nodico_long, "GLM", "no_dico")

# Unir todos
df_plot <- bind_rows(rf_dico_long, rf_nodico_long, glm_dico_long, glm_nodico_long)
df_plot_filtrado <- df_plot %>%
  filter(Metric %in% c("Accuracy", "Kappa", "Sensitivity", "Specificity", "AUC"))

# Graficar
grafico_prueba<-ggplot(df_plot_filtrado, aes(x = Algorithm, y = value, color = Tipo)) +
  geom_point(position = position_jitter(width = 0.15), alpha = 0.8, size = 2) +
  facet_wrap(~ Metric, scales = "free_y") +
  theme_minimal() +
  labs(
    title = "Performance de las metricas por algoritmo y dicotomizacion",
    subtitle = "dico = binarized, no_dico = original intensities",
    x = "Algorithm",
    y = "Value",
    color = "Tipo de dato"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(face = "bold")
  )

save(grafico_prueba, file = "grafico_prueba.rda")
```


```{r}
names(rf_dico)
str(rf_dico)

```


```{r}
saveRDS(rf_dico, "rf_dico.rds")
saveRDS(rf_nodico, "rf_nodico.rds")
saveRDS(glm_dico, "glm_dico.rds")
saveRDS(glm_nodico, "glm_nodico.rds")
saveRDS(glm_nodico, "df_plot_filtrado.rds")

```

