---
title: "fecha"
author: "Karina Roitman"
date: "2025-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MALDIquant)
library(MALDIquantForeign)
library(readBrukerFlexData)
library(ggplot2)
library(caret)
library(stats)
library(binda)
library(factoextra)
library(binda)
library(dplyr)
library(crossval)
library(ggrepel)
library(corrr)
library(ggplot2)
library(FactoMineR)
```


# Modelos (con datos combat_corrected POR FECHA dicotomizado)

```{r}
Datos_actualizados<-datos_filtrados

combat_corrected_fecha_high<-as.data.frame(combat_corrected_fecha_high)
combat_corrected_fecha_high_tot<- cbind(combat_corrected_fecha_high, label=Datos_actualizados$PCR.Cov)#1=neg,2=pos
combat_corrected_fecha_high_tot<-as.data.frame(combat_corrected_fecha_high_tot)
combat_corrected_fecha_high_tot$label <- as.factor(combat_corrected_fecha_high_tot$label)
```

```{r}
combat_corrected_fecha_dico_high<-combat_corrected_fecha_high_tot[1:238,]

ciego_combat_corrected_fecha_dico_high<-combat_corrected_fecha_high_tot[239:327,]

```


```{r}

library(tidymodels)
# set.seed asegura reproducibilidad
set.seed(42)

#Utilizo tidymodels para dividir de manera proporcional

split_data <- initial_split(combat_corrected_fecha_dico_high, strata = "label", prop = 0.8)

# Obtener los conjuntos de entrenamiento y prueba
trainData_fecha_dico <- training(split_data)
testData_fecha_dico <- testing(split_data)

```

```{r}
trainData_fecha_dico<-as.data.frame(trainData_fecha_dico)
trainData_fecha_dico$label<-as.factor(trainData_fecha_dico$label)
str(trainData_fecha_dico)
```

```{r}
#trainData_fecha_dico<-trainData_fecha_dico[, 1:64]
train_subset_fecha <- trainData_fecha_dico[, -ncol(trainData_fecha_dico)]
```


```{r}
library(dplyr)
trainData_fecha_dico <- trainData_fecha_dico %>% rename(Y = label)
#trainData_fecha_dico<-trainData_fecha_dico[,-ncol(trainData_fecha_dico)]
str(trainData_fecha_dico$Y)
```


```{r}
#Dicotimizacion de la matriz de intensidad
 #optimizeThreshold uses (approximate) mutual information to determine the optimal thresholds. Specifically, the thresholds are chosen to maximize the mutual information between response and each variable
thr <- optimizeThreshold(train_subset_fecha, trainData_fecha_dico$Y)
train_subset_fecha <- dichotomize(train_subset_fecha, thr) #2 MATRIZ DE INTENSIDAD DICOTOMIZADA

```


```{r}
trainData_fecha_dico<- cbind(train_subset_fecha, trainData_fecha_dico$Y)#1=neg,2=pos
```



```{r}
str(trainData_fecha_dico)
trainData_fecha_dico<-as.data.frame(trainData_fecha_dico)
```





```{r}
library(dplyr)
trainData_fecha_dico <- trainData_fecha_dico %>% rename(Y = ncol(trainData_fecha_dico))
str(trainData_fecha_dico$Y)
```


```{r}
trainData_fecha_dico<-as.data.frame(trainData_fecha_dico)
trainData_fecha_dico$Y<-as.factor(trainData_fecha_dico$Y)
str(trainData_fecha_dico)
```



```{r}
zero_var_indices <- nearZeroVar(trainData_fecha_dico[, -ncol(trainData_fecha_dico)])
#train_subset_fecha <- train_subset_fecha
if (length(zero_var_indices) > 0) {
    trainData_fecha_dico <- trainData_fecha_dico[, -zero_var_indices]
}


```
QUEDAN 38 VARIABLES

```{r}

thr_filtered <- thr[colnames(trainData_fecha_dico[,-ncol(trainData_fecha_dico)])]
```


```{r}
#trainData_fecha_dico <- cbind(train_subset_fecha, trainData_fecha_dico$Y)
```




```{r}
#library(dplyr)
#trainData_fecha_dico<-as.data.frame(trainData_fecha_dico)
#trainData_fecha_dico <- trainData_fecha_dico %>% rename(Y = V42)
#str(trainData_fecha_dico$Y)
```



```{r}
testData_fecha_dico<-as.data.frame(testData_fecha_dico)
testData_fecha_dico$label<-as.factor(testData_fecha_dico$label)

str(testData_fecha_dico)
```



```{r}
library(dplyr)
#testData_fecha_dico<-testData_fecha_dico[,c(1:64)]
testData_fecha_dico <- testData_fecha_dico %>% rename(Y = label)
str(testData_fecha_dico$Y)
```


```{r}
test_subset_fecha <- testData_fecha_dico[, -ncol(testData_fecha_dico)]
```



```{r}
test_subset_fecha <-  test_subset_fecha[, colnames(trainData_fecha_dico[,-ncol(trainData_fecha_dico)])]


#test_subset <-  test_subset[, colnames(trainData_equipo_dico)]

#Dicotimizacion de la matriz de intensidad
test_subset_fecha <- dichotomize(test_subset_fecha, thr_filtered) 


```


```{r}
testData_fecha_dico<- cbind(test_subset_fecha, testData_fecha_dico$Y)#1=neg,2=pos
```

```{r}
library(dplyr)
testData_fecha_dico<-as.data.frame(testData_fecha_dico)
testData_fecha_dico <- testData_fecha_dico %>% rename(Y = ncol(testData_fecha_dico))
str(testData_fecha_dico$Y)
```


```{r}
testData_fecha_dico<-as.data.frame(testData_fecha_dico)
testData_fecha_dico$Y<-as.factor(testData_fecha_dico$Y)
str(testData_fecha_dico)
```




```{r}
trainData_fecha_dico<-as.data.frame(trainData_fecha_dico)
trainData_fecha_dico$Y<-as.factor(trainData_fecha_dico$Y)
testData_fecha_dico<-as.data.frame(testData_fecha_dico)
# Ver la distribución de clases en ambos conjuntos
table(trainData_fecha_dico$Y)
table(testData_fecha_dico$Y)


```






```{r}
library(caret)
#set.seed(42)
#control1 <- trainControl(method = "cv", number = 5)
#en esta primera vez pruebo con crossval
```

```{r}
# Especificar la variable dependiente en la fórmula
formula <- Y ~ .
```




```{r}
# Submuestras y repeticiones
set.seed(42)
# particiones  <- 5
# repeticiones <- 15
particiones <- 3
repeticiones <- 5
```

```{r}
# Specify the tunning configuration (mtry hyperparameter depends on the number of columns)
seed.rf <- 42
set.seed(seed.rf) 


mtry <- c(2, 5, 10)
min.node.size <- seq(1, 10, 2)  # Reducir el rango
hiperparametros <- expand.grid(mtry =  mtry)
                               #min.node.size = seq(1, 30, 2),
                               #min.node.size=min.node.size,
                               #splitrule = "gini")
```


```{r}

# Seeds
seed.rf <- 42
set.seed(seed.rf)

seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(500, nrow(hiperparametros)) 
}
# genera un vector de nrow(hiperparametros) números aleatorios entre 1 y 500.
#Esto asegura que cada combinación de hiperparámetros tenga una semilla diferente en cada iteración.

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# Training control

cross_val_rf <- trainControl(
  method = "repeatedcv",
  number = particiones,
  repeats = repeticiones,
  returnResamp = "final",
  verboseIter = FALSE,
  allowParallel = TRUE,
  classProbs = TRUE,
  seeds = seeds)

# Training 

# Convertir los niveles de Train.rf$sensi a números también

trainData_fecha_dico$Y <- factor(as.numeric(factor(trainData_fecha_dico$Y)))
trainData_fecha_dico$Y <- factor(trainData_fecha_dico$Y, levels = c("1", "2"))
levels(trainData_fecha_dico$Y) <- make.names(levels(trainData_fecha_dico$Y))

```



# Random forest

```{r}
class(trainData_fecha_dico)
```


```{r}
trainData_fecha_dico$Y <- factor(as.numeric(factor(trainData_fecha_dico$Y)))
trainData_fecha_dico$Y <- factor(trainData_fecha_dico$Y, levels = c("1", "2"))
levels(trainData_fecha_dico$Y) <- make.names(levels(trainData_fecha_dico$Y))
library(caret)
#control1 <- trainControl(method = "cv", number = 10)
#grid_rf <- expand.grid(mtry = c(2, 5, 10)) #the randomForest package only has one available tuning parameter, )
# rf_fecha_dic <- caret::train(Y ~ ., data = trainData_fecha_dico, 
#                       method = "rf",   # Método para random forest
#                       trControl = cross_val, 
#                       tuneGrid = grid_rf,  # Parámetro mtry
#                       metric = "Accuracy")  # Métrica para clasificación


RF_fecha_carga_fx <- function(df_train, model, grid, metrica = "Accuracy",  control) {

  # Entrenar el modelo
  rf_fecha_dic <- caret::train(
    Y ~ .,
    data = df_train,
    method = model,
    tuneGrid = grid,
    metric = metrica,
    trControl = control
  )
  
  # Mostrar resumen
  print(rf_fecha_dic)
  plot(rf_fecha_dic, main = title)
  
  # Guardar resultado
  #save(RF_equipo, file = paste0(title, ".rda"))
  
  return(rf_fecha_dic)
}

rf_fecha_dic<-RF_fecha_carga_fx(df_train=trainData_fecha_dico, model="rf", grid=hiperparametros, metrica="Accuracy", control= cross_val_rf )
print(rf_fecha_dic)
```

```{r}
rf_fecha_dic$results
```

```{r}
plot(rf_fecha_dic)
```


# ranger


combat_corrected_fecha_high_DICHO

```{r}
Train.rf_fecha_dico  <- as.data.frame(trainData_fecha_dico) 

Test.rf_fecha_dico <- as.data.frame(testData_fecha_dico)
```

```{r}
y_train <- Train.rf_fecha_dico$Y
x_train <- Train.rf_fecha_dico[, setdiff(names(Train.rf_fecha_dico), "Y")]
y_test <- Test.rf_fecha_dico$Y
x_test <- Test.rf_fecha_dico[, setdiff(names(Test.rf_fecha_dico), "Y")]

# Crear el objeto recipe solo con las variables predictoras
objeto_recipe <- recipe(Y ~ ., data = Train.rf_fecha_dico)

# Preparar el objeto recipe
trained_recipe <- prep(objeto_recipe, training = Train.rf_fecha_dico)

# Aplicar bake solo a las variables predictoras
x_train_baked <- bake(trained_recipe, new_data = x_train)
x_test_baked <- bake(trained_recipe, new_data = x_test)

# Volver a juntar Y con los datos procesados
Train.rf_fecha_dico <- cbind(x_train_baked, Y = y_train)
Test.rf_fecha_dico <- cbind(x_test_baked, Y = y_test)

```

```{r}
# Submuestras y repeticiones

# particiones  <- 5
# repeticiones <- 15
particiones <- 3
repeticiones <- 5
```

```{r}
# Specify the tunning configuration (mtry hyperparameter depends on the number of columns)
seed.rf <- 42
set.seed(seed.rf) 


mtry <- c(1, 2, 3)
min.node.size <- seq(1, 10, 2)  # Reducir el rango
hiperparametros <- expand.grid(mtry =  mtry,
                               #min.node.size = sfecha(1, 30, 2),
                               min.node.size=min.node.size,
                               splitrule = "gini")
```


```{r}

# Seeds
seed.rf <- 42
set.seed(seed.rf)

seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(500, nrow(hiperparametros)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# Training control

cross_val_ranger <- trainControl(
  method = "repeatedcv",
  number = particiones,
  repeats = repeticiones,
  returnResamp = "final",
  verboseIter = FALSE,
  allowParallel = TRUE,
  classProbs = TRUE,
  seeds = seeds)

# Training 

# Convertir los niveles de Train.rf$sensi a números también

Train.rf_fecha_dico$Y <- factor(as.numeric(factor(Train.rf_fecha_dico$Y)))
Train.rf_fecha_dico$Y <- factor(Train.rf_fecha_dico$Y, levels = c("1", "2"))
levels(Train.rf_fecha_dico$Y) <- make.names(levels(Train.rf_fecha_dico$Y))

```





```{r}
class(Train.rf_fecha_dico)
```


```{r}
Train.rf_fecha_dico <- as.data.frame(Train.rf_fecha_dico)
```


```{r}
# Primero aseguramos que Train.rf es un dataframe
Train.rf_fecha_dico <- as.data.frame(Train.rf_fecha_dico)

# Convertimos Y a factor
Train.rf_fecha_dico$Y <- as.factor(Train.rf_fecha_dico$Y)

# Definimos número de árboles
#n_trees <- 500 # default
n_trees<-200
# Establecemos semilla para reproducibilidad
set.seed(80)

# Ejecutamos el entrenamiento
results_ranger_fecha_dic <- caret::train(Y ~ .,
                data = Train.rf_fecha_dico, 
                method = "ranger",
                tuneGrid = hiperparametros,
                metric = "Accuracy",
                importance = "impurity",
                trControl = cross_val,
                num.trees = n_trees)
               #allowParallel=FALSE)  # Aquí estaba el error, había texto adicional

# Vector para probar diferentes números de árboles
#num_trees_range <- c(10, 50, 100, 200, 500, 1000, 1500)

```


```{r}
# Definir los valores de num.trees a probar
num_trees_range <- c(10, 50, 100, 200, 500, 1000, 1500)

# Lista para almacenar los modelos
modelos_fecha_dico <- list()

# Establecer semilla para reproducibilidad
set.seed(80)

# Iterar sobre cada cantidad de árboles
for (nt in num_trees_range) {
  cat("Entrenando modelo con", nt, "árboles...\n")
  
  modelos_fecha_dico[[as.character(nt)]] <- caret::train(
    Y ~ .,
    data = Train.rf_fecha_dico,
    method = "ranger",
    tuneGrid = hiperparametros,
    metric = "Accuracy",
    importance = "impurity",
    trControl = cross_val,
    num.trees = nt
  )
}
```





```{r}
  resultados_modelos <- data.frame(
  num_trees = num_trees_range,
  Accuracy = sapply(modelos_fecha_dico, function(m) max(m$results$Accuracy, na.rm = TRUE)),
  Kappa = sapply(modelos_fecha_dico, function(m) max(m$results$Kappa, na.rm = TRUE)),
  mtry = sapply(modelos_fecha_dico, function(m) m$bestTune$mtry),
  min.node.size = sapply(modelos_fecha_dico, function(m) m$bestTune$min.node.size)
)

# Ordenamos los modelos de mejor a peor Accuracy
resultados_modelos <- resultados_modelos[order(-resultados_modelos$Accuracy), ]

print(head(resultados_modelos, 20)) 

```


```{r}
# Encontrar el índice del modelo con mejor Accuracy en la tabla de resultados
mejor_idx <- which.max(resultados_modelos$Accuracy)

# Extraer la mejor combinación de hiperparámetros
mejor_num_trees <- resultados_modelos$num_trees[mejor_idx]
mejor_mtry <- resultados_modelos$mtry[mejor_idx]
mejor_min_node_size <- resultados_modelos$min.node.size[mejor_idx]

# Extraer el modelo correspondiente en la lista
mejor_modelo <- modelos_fecha_dico[[as.character(mejor_num_trees)]]

# Mostrar los hiperparámetros seleccionados
cat("Mejor modelo seleccionado:\n")
cat("Número de árboles:", mejor_num_trees, "\n")
cat("mtry:", mejor_mtry, "\n")
cat("min.node.size:", mejor_min_node_size, "\n")

# Mostrar detalles del mejor modelo
print(mejor_modelo)

```

```{r}
# ranger_fecha_dico <- caret::train(
#   Y ~ .,
#   data = Train.rf_fecha_dico, 
#   method = "ranger",
#   tuneGrid = data.frame(mtry = 3, min.node.size = 9, splitrule = "gini"), 
#   metric = "Accuracy",
#   importance = "impurity",
#   trControl = cross_val,  # Si querés usar validación cruzada
#   num.trees = 500  # Número de árboles fijo
# )
# print(ranger_fecha_dico)
ranger_fecha_dicocarga_fx<-function(df_train, model, grid, metrica,  num.trees){

ranger_fecha_dico <- caret::train(
  Y ~ .,
  data = df_train,
  method = model,
  tuneGrid = grid,
  metric = metrica,
  importance = "impurity",
  trControl = cross_val_ranger,  # Si querés usar validación cruzada
  num.trees=num.trees  # Número de árboles fijo
)

return(ranger_fecha_dico)
}

#

ranger_fecha_dico<-ranger_fecha_dicocarga_fx(Train.rf_fecha_dico, model="ranger",hiperparametros,"Accuracy", num.trees=mejor_num_trees)
```



```{r}
Test.rf_fecha_dico$Y<-as.factor(Test.rf_fecha_dico$Y)
str(Test.rf_fecha_dico$Y)
```

```{r}
testRF_NOID_fecha_dico <- Test.rf_fecha_dico[, -which(names(Test.rf_fecha_dico) == "Y")]

```



```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predRANGER_fecha_dic_carga<-predict(ranger_fecha_dico, newdata = testRF_NOID_fecha_dico)#matriz binarizada
print(predRANGER_fecha_dic_carga)

predRANGER_fecha_dic_carga <- factor(as.character(predRANGER_fecha_dic_carga), 
                             levels = c("X1", "X2"),
                             labels = c("1", "2"))
predRANGER_fecha_dic_carga <- factor(predRANGER_fecha_dic_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))
y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))

# Obtener las etiquetas reales del conjunto de datos de prueba
#y_test <- testData$Y

prob_predRanger_fecha_dic <- predict(ranger_fecha_dico, newdata = testRF_NOID_fecha_dico, type = "prob")

colnames(prob_predRanger_fecha_dic)
# Asegúrate de que y_test sea un factor con los niveles correctos
y_test <- factor(Test.rf_fecha_dico$Y, levels = c(1, 2), labels = c("Cov.Neg", "Cov.Pos"))




```


```{r}
library(pROC)

# Asegúrate de que y_test sea numérico y esté alineado con los niveles 1 y 2
y_test_numeric <- as.numeric(y_test)

roc_curve <- roc(response = y_test_numeric, 
                 predictor = prob_predRanger_fecha_dic[, "X2"], 
                 levels = c(1, 2))
AUC_Ranger_FECHA_dich_carga <- auc(roc_curve)
print(paste("El valor de AUC es:", round(AUC_Ranger_FECHA_dich_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve, main = "Curva ROC", col = "blue", lwd = 2)

# confusion_matrixRANGER <- table(predRANGER_fecha_dic, y_test)
# # Imprimir la matriz de confusión
# print(confusion_matrixRANGER)
Ranger_metrics_fehca_dic_carga <- caret::confusionMatrix(predRANGER_fecha_dic_carga, y_test, positive = "Cov.Pos")
```


```{r}
library(caret)
accuracyRANGER_fecha_dic_carga<- Ranger_metrics_fehca_dic_carga$overall["Accuracy"]
kappaRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$overall["Kappa"]
# Métricas por clase
sensitivityRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Sensitivity"]
specificityRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Specificity"]
precisionRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Pos Pred Value"]
recallRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["F1"]
npvRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Neg Pred Value"]
prevalenceRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Prevalence"]
detection_rateRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Detection Rate"]
balanced_accuracyRANGER_fecha_dic_carga <- Ranger_metrics_fehca_dic_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusRANGER_fecha_dic_carga <- sensitivityRANGER_fecha_dic_carga / (1 - specificityRANGER_fecha_dic_carga)
LR_minusRANGER_fecha_dic_carga <- (1 - sensitivityRANGER_fecha_dic_carga) / specificityRANGER_fecha_dic_carga

# Para manejar valores especiales
LR_plusRANGER_fecha_dic_carga <- ifelse(is.nan(LR_plusRANGER_fecha_dic_carga) | is.infinite(LR_plusRANGER_fecha_dic_carga), NA, LR_plusRANGER_fecha_dic_carga)
LR_minusRANGER_fecha_dic_carga <- ifelse(is.nan(LR_minusRANGER_fecha_dic_carga) | is.infinite(LR_minusRANGER_fecha_dic_carga), NA, LR_minusRANGER_fecha_dic_carga)

# Crear un dataframe con todas las métricas
metricsRANGER_fecha_dic_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  RANGER_fecha_dic_carga = c(accuracyRANGER_fecha_dic_carga, kappaRANGER_fecha_dic_carga, sensitivityRANGER_fecha_dic_carga, specificityRANGER_fecha_dic_carga, precisionRANGER_fecha_dic_carga, 
            f1_scoreRANGER_fecha_dic_carga, npvRANGER_fecha_dic_carga, prevalenceRANGER_fecha_dic_carga, detection_rateRANGER_fecha_dic_carga, 
            balanced_accuracyRANGER_fecha_dic_carga, LR_plusRANGER_fecha_dic_carga, LR_minusRANGER_fecha_dic_carga, AUC_Ranger_FECHA_dich_carga))

# Mostrar los resultados
print(metricsRANGER_fecha_dic_carga)

# Precisión (Accuracy)
# accuracy_RANGER_fecha_dic <- sum(diag(confusion_matrixRANGER)) / sum(confusion_matrixRANGER)
# print(paste("La precisión (Accuracy) es:", round(accuracy_RANGER_fecha_dic,2)))
# 
# # Sensibilidad (Recall o TPR)
# sensitivity_RANGER_fecha_dic <- confusion_matrixRANGER[2, 2] / sum(confusion_matrixRANGER[, 2])
# print(paste("La sensibilidad es:", round(sensitivity_RANGER_fecha_dic,2)))
# 
# # Especificidad (TNR)
# specificity_RANGER_fecha_dic <- confusion_matrixRANGER[1, 1] / sum(confusion_matrixRANGER[, 1])
# print(paste("la especificidad es:", round(specificity_RANGER_fecha_dic,2)))
# 
# # Valor Predictivo Positivo (PPV o Precision)
# ppv_RANGER_fecha_dic <- confusion_matrixRANGER[2, 2] / sum(confusion_matrixRANGER[2, ])
# print(paste("el VPP es:", round(ppv_RANGER_fecha_dic,2)))
# 
# # Valor Predictivo Negativo (VPN)
# npv_RANGER_fecha_dic <- confusion_matrixRANGER[1, 1] / sum(confusion_matrixRANGER[1, ])
# print(paste("el VPN es: ",  round(npv_RANGER_fecha_dic,2)))


```




# KNN


```{r}
tuneGrid <- expand.grid(k = 1:15)
# Seeds
seed.rf <- 42
set.seed(seed.rf)

seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(500, nrow(tuneGrid)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# Training control

cross_val_knn <- trainControl(
  method = "repeatedcv",
  number = particiones,
  repeats = repeticiones,
  returnResamp = "final",
  verboseIter = FALSE,
  allowParallel = TRUE,
  classProbs = TRUE,
  seeds = seeds)
```


```{r}
# 
# #set.seed(42)
# # Ajustar el modelo KNN
# KNN_fecha_dic <- caret::train(formula, 
#                     data = trainData_fecha_dico, 
#                     trControl = cross_val, 
#                     method = "knn", 
#                     metric = "Accuracy", 
#                     preProcess = c("center","scale"),
#                     tuneGrid = tuneGrid)
# 
# KNN_fecha_dic
KNN_fecha_carga_dic_fx <- function(df_train, model, grid, metrica = "Accuracy",  control, preProcess) {

  
  # Entrenar el modelo
  KNN_fecha_dic <- caret::train(
    Y ~ .,
    data = df_train,
    method = model,
    tuneGrid = grid,
    metric = metrica,
    trControl = control,
    preProcess = preProcess
  )
  
  # Mostrar resumen
  print(KNN_fecha_dic)
  plot(KNN_fecha_dic, main = title)
  
  # Guardar resultado
  #save(KNN_fecha_tot_fx, file = paste0(title, ".rda"))
  
  return(KNN_fecha_dic)
}

KNN_fecha_dic<-KNN_fecha_carga_dic_fx(df_train=trainData_fecha_dico, model="knn", grid=tuneGrid, metrica="Accuracy",   control= cross_val_knn, preProcess = c("center","scale") )
print(KNN_fecha_dic)
```

```{r}
plot(KNN_fecha_dic)
```

# GLMNET


```{r}

tuneGrid <- expand.grid(
  alpha = seq(0, 1, by = 0.1),  # From 0 (Ridge) to 1 (Lasso)
  lambda = 10^seq(-3, 3, length = 100)  # Logarithmic scale for lambda
)
# Seeds
seed.rf <- 42
set.seed(seed.rf)
max_sample <- max(500, nrow(tuneGrid) * 2)
seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(max_sample, nrow(tuneGrid)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# Training control

cross_val_glm <- trainControl(
  method = "repeatedcv",
  number = particiones,
  repeats = repeticiones,
  returnResamp = "final",
  verboseIter = FALSE,
  allowParallel = TRUE,
  classProbs = TRUE,
  seeds = seeds)
```



```{r}

# GLM_fecha_dic<- caret::train(formula, 
#                   data = trainData_fecha_dico,  
#                    method = "glmnet",
#                    metric = "Accuracy",
#                    tuneLength = 3,
#                    trControl = cross_val,
#                   tuneGrid=tuneGrid)
# 
# GLM_fecha_dic 

GLM_fecha_diccarga_fx <- function(df_train, model, grid, metrica = "Accuracy", control) {

  
  # Entrenar el modelo
  GLM_fecha_dic <- caret::train(
    Y ~ .,
    data = df_train,
    method = model,
    tuneGrid = grid,
    metric = metrica,
    trControl = cross_val_glm
  )
  
  # Mostrar resumen
  print(GLM_fecha_dic)
  plot(GLM_fecha_dic, main = title)
  
  # Guardar resultado
  #save(GLM_fecha_dic, file = paste0(title, ".rda"))
  
  return(GLM_fecha_dic)
}

GLM_fecha_dic<-GLM_fecha_diccarga_fx(df_train=trainData_fecha_dico, model="glmnet", grid=tuneGrid, metrica="Accuracy")
print(GLM_fecha_dic)
```

```{r}
# Imprimir los mejores hiperparámetros
best_params <- GLM_fecha_dic$bestTune
print("Best Hyperparameters:")
print(best_params)

# Extraer accuracy y kappa del mejor modelo
# Buscamos la fila que corresponde a los mejores hiperparámetros en el data frame model$results
best_model_index <- apply(GLM_fecha_dic$results, 1, function(row) {
  all(row[1:length(best_params)] == as.numeric(best_params))
})

best_model_results <- GLM_fecha_dic$results[best_model_index, ]

# Imprimir accuracy y kappa del mejor modelo
accuracy <- best_model_results$Accuracy
kappa <- best_model_results$Kappa

print("Accuracy of the Best Model:")
print(accuracy)

print("Kappa of the Best Model:")
print(kappa)

```

# Predicciones

```{r}
testData_fecha_dico$Y<-as.factor(testData_fecha_dico$Y)
str(testData_fecha_dico$Y)
```

```{r}
testData_NOID_fecha_dico <- testData_fecha_dico[, -which(names(testData_fecha_dico) == "Y")]

```

# RF

```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predRF_fecha_dic_carga<-predict(rf_fecha_dic, newdata = testData_NOID_fecha_dico)#matriz binarizada
print(predRF_fecha_dic_carga)

predRF_fecha_dic_carga <- factor(as.character(predRF_fecha_dic_carga), 
                             levels = c("X1", "X2"),
                             labels = c("1", "2"))
predRF_fecha_dic_carga <- factor(predRF_fecha_dic_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))
y_test <- testData_equipo$Y
#y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))

# Obtener las etiquetas reales del conjunto de datos de prueba
#y_test <- testData$Y

prob_predRF_fechadic <- predict(rf_fecha_dic, newdata = testData_NOID_fecha_dico, type = "prob")

colnames(prob_predRF_fechadic)
# Asegúrate de que y_test sea un factor con los niveles correctosy_test <- factor(testData_fecha_dico$Y, levels = c(1, 2), labels = c("Cov.Neg", "Cov.Pos"))




```


```{r}
library(pROC)

# Asegúrate de que y_test sea numérico y esté alineado con los niveles 1 y 2
y_test_numeric <- as.numeric(y_test)

roc_curve <- roc(response = y_test_numeric, predictor = prob_predRF_fechadic[, "X2"], levels = c(1, 2))
AUC_RF_fecha_dic_carga <- auc(roc_curve)

print(paste("El valor de AUC es:", round(AUC_RF_fecha_dic_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve, main = "Curva ROC", col = "blue", lwd = 2)
```


```{r}
# confusion_matrixRF <- table(predRF_fecha_dic, y_test)
# # Imprimir la matriz de confusión
# print(confusion_matrixRF)
RF_metrics_fecha_dico_carga <- caret::confusionMatrix(predRF_fecha_dic_carga, y_test, positive = "Cov.Pos")
```

```{r}
library(caret)
accuracyRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$overall["Accuracy"]
kappaRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$overall["Kappa"]
# Métricas por clase
sensitivityRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Sensitivity"]
specificityRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Specificity"]
precisionRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Pos Pred Value"]
recallRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["F1"]
npvRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Neg Pred Value"]
prevalenceRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Prevalence"]
detection_rateRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Detection Rate"]
balanced_accuracyRF_fecha_dic_carga <- RF_metrics_fecha_dico_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusRF_fecha_dic_carga <- sensitivityRF_fecha_dic_carga / (1 - specificityRF_fecha_dic_carga)
LR_minusRF_fecha_dic_carga <- (1 - sensitivityRF_fecha_dic_carga) / specificityRF_fecha_dic_carga

# Para manejar valores especiales
LR_plusRF_fecha_dic_carga <- ifelse(is.nan(LR_plusRF_fecha_dic_carga) | is.infinite(LR_plusRF_fecha_dic_carga), NA, LR_plusRF_fecha_dic_carga)


LR_minusRF_fecha_dic_carga <- ifelse(is.nan(LR_minusRF_fecha_dic_carga) | is.infinite(LR_minusRF_fecha_dic_carga), NA, LR_minusRF_fecha_dic_carga)

# Crear un dataframe con todas las métricas
metricsRF_fecha_dic_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  RF_fecha_dic_carga = c(accuracyRF_fecha_dic_carga, kappaRF_fecha_dic_carga, sensitivityRF_fecha_dic_carga, specificityRF_fecha_dic_carga, precisionRF_fecha_dic_carga, 
            f1_scoreRF_fecha_dic_carga, npvRF_fecha_dic_carga, prevalenceRF_fecha_dic_carga, detection_rateRF_fecha_dic_carga, 
            balanced_accuracyRF_fecha_dic_carga, LR_plusRF_fecha_dic_carga, LR_minusRF_fecha_dic_carga, AUC_RF_fecha_dic_carga))

# Mostrar los resultados
print(metricsRF_fecha_dic_carga)


```



# Prediccion GLM

```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predGLM_fecha_dic_carga<-predict(GLM_fecha_dic, newdata = testData_NOID_fecha_dico)#matriz binarizada
print(predGLM_fecha_dic_carga)

predGLM_fecha_dic_carga <- factor(as.character(predGLM_fecha_dic_carga), 
                             levels = c("X1", "X2"),
                             labels = c("1", "2"))
predGLM_fecha_dic_carga <- factor(predGLM_fecha_dic_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))


# Obtener las etiquetas reales del conjunto de datos de prueba
y_test <- testData_fecha_dico$Y
#y_testDIC <- FeatureMatrix_Dic_df$Y#Matriz binarizada
y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))
```

```{r}
# confusion_matrixGLM <- table(predGLM_fecha_dic, y_test)
# # Imprimir la matriz de confusión
# print(confusion_matrixGLM)
GLM_metrics_fecha_dico_carga <- caret::confusionMatrix(predGLM_fecha_dic_carga, y_test, positive = "Cov.Pos")
```


```{r}


# Predicciones probabilísticas con el modelo GLM
prob_predGLM <- predict(GLM_fecha_dic, newdata = testData_NOID_fecha_dico, type = "prob")

# Verifica los nombres de las columnas (clases)
print(colnames(prob_predGLM))  # Deberían ser "1" y "2" o los nombres de las clases

# Asegúrate de que y_test sea numérico con niveles 1 y 2
y_test_numeric <- as.numeric(testData_fecha_dico$Y)

# Calcula la curva ROC usando la probabilidad de la clase positiva ("2")
roc_curve_glm <- roc(response = y_test_numeric, predictor = prob_predGLM[, "X2"], levels = c(1, 2))

# Calcula el AUC
AUC_GLM_fecha_dic_carga <- auc(roc_curve_glm)
print(paste("El valor de AUC es:", round(AUC_GLM_fecha_dic_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve_glm, main = "Curva ROC - GLM", col = "red", lwd = 2)
```
```{r}
library(caret)
accuracyGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$overall["Accuracy"]
kappaGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$overall["Kappa"]
# Métricas por clase
sensitivityGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Sensitivity"]
specificityGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Specificity"]
precisionGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Pos Pred Value"]
recallGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["F1"]
npvGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Neg Pred Value"]
prevalenceGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Prevalence"]
detection_rateGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Detection Rate"]
balanced_accuracyGLM_fecha_dic_carga <- GLM_metrics_fecha_dico_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusGLM_fecha_dic_carga <- sensitivityGLM_fecha_dic_carga / (1 - specificityGLM_fecha_dic_carga)
LR_minusGLM_fecha_dic_carga <- (1 - sensitivityGLM_fecha_dic_carga) / specificityGLM_fecha_dic_carga

# Para manejar valores especiales
LR_plusGLM_fecha_dic_carga <- ifelse(is.nan(LR_plusGLM_fecha_dic_carga) | is.infinite(LR_plusGLM_fecha_dic_carga), NA, LR_plusGLM_fecha_dic_carga)
LR_minusGLM_fecha_dic_carga <- ifelse(is.nan(LR_minusGLM_fecha_dic_carga) | is.infinite(LR_minusGLM_fecha_dic_carga), NA, LR_minusGLM_fecha_dic_carga)

# Crear un dataframe con todas las métricas
metricsGLM_fecha_dic_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  GLM_fecha_dic_carga = c(accuracyGLM_fecha_dic_carga, kappaGLM_fecha_dic_carga, sensitivityGLM_fecha_dic_carga, specificityGLM_fecha_dic_carga, precisionGLM_fecha_dic_carga, 
            f1_scoreGLM_fecha_dic_carga, npvGLM_fecha_dic_carga, prevalenceGLM_fecha_dic_carga, detection_rateGLM_fecha_dic_carga, 
            balanced_accuracyGLM_fecha_dic_carga, LR_plusGLM_fecha_dic_carga, LR_minusGLM_fecha_dic_carga, AUC_GLM_fecha_dic_carga))

# Mostrar los resultados
print(metricsGLM_fecha_dic_carga)

# library(irr)
# 
# # Calcular Kappa
# kappa_GLM_fecha_dic <- kappa2(cbind(predGLM_fecha_dic, testData_fecha_dico$Y))
# 
# # Ver el valor de Kappa
# print(paste("El índice Kappa es:", round(kappa_GLM_fecha_dic$value, 3)))
# kappa_GLM_fecha_dic<-round(kappa_GLM_fecha_dic$value, 3)
```




# Prediccion KNN

```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predKNN_fecha_dic_carga<-predict(KNN_fecha_dic, newdata = testData_NOID_fecha_dico)#matriz binarizada
print(predKNN_fecha_dic_carga)

predKNN_fecha_dic_carga <- factor(as.character(predKNN_fecha_dic_carga), 
                             levels = c("X1", "X2"),
                             labels = c("1", "2"))
predKNN_fecha_dic_carga <- factor(predKNN_fecha_dic_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))


# Obtener las etiquetas reales del conjunto de datos de prueba
y_test <- testData_fecha_dico$Y
#y_testDIC <- FeatureMatrix_Dic_df$Y#Matriz binarizada
y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))
```

```{r}
KNN_metrics_fecha_dico_carga <- caret::confusionMatrix(predKNN_fecha_dic_carga, y_test, positive = "Cov.Pos")
```

```{r}


prob_predKNN_fecha <- predict(KNN_fecha_dic, newdata = testData_NOID_fecha_dico, type = "prob")

# Verifica los nombres de las columnas (clases)
print(colnames(prob_predKNN_fecha))  # Deberían ser "1" y "2" o los nombres de las clases

# Asegúrate de que y_test sea numérico con niveles 1 y 2
y_test_numeric <- as.numeric(testData_fecha_dico$Y)

# Calcula la curva ROC usando la probabilidad de la clase positiva ("2")
roc_curve_knn <- roc(response = y_test_numeric, predictor = prob_predKNN_fecha[, "X2"], levels = c(1, 2))

# Calcula el AUC
AUC_KNN_fecha_dic_carga <- auc(roc_curve_knn)
print(paste("El valor de AUC es:", round(AUC_KNN_fecha_dic_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve_knn, main = "Curva ROC - KNN", col = "blue", lwd = 2)
```


```{r}
library(caret)
accuracyKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$overall["Accuracy"]
kappaKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$overall["Kappa"]
# Métricas por clase
sensitivityKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Sensitivity"]
specificityKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Specificity"]
precisionKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Pos Pred Value"]
recallKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["F1"]
npvKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Neg Pred Value"]
prevalenceKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Prevalence"]
detection_rateKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Detection Rate"]
balanced_accuracyKNN_fecha_dic_carga <- KNN_metrics_fecha_dico_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusKNN_fecha_dic_carga <- sensitivityKNN_fecha_dic_carga / (1 - specificityKNN_fecha_dic_carga)
LR_minusKNN_fecha_dic_carga <- (1 - sensitivityKNN_fecha_dic_carga) / specificityKNN_fecha_dic_carga

# Para manejar valores especiales
LR_plusKNN_fecha_dic_carga <- ifelse(is.nan(LR_plusKNN_fecha_dic_carga) | is.infinite(LR_plusKNN_fecha_dic_carga), NA, LR_plusKNN_fecha_dic_carga)
LR_minusKNN_fecha_dic_carga <- ifelse(is.nan(LR_minusKNN_fecha_dic_carga) | is.infinite(LR_minusKNN_fecha_dic_carga), NA, LR_minusKNN_fecha_dic_carga)

# Crear un dataframe con todas las métricas
metricsKNN_fecha_dic_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  KNN_fecha_dic_carga = c(accuracyKNN_fecha_dic_carga, kappaKNN_fecha_dic_carga, sensitivityKNN_fecha_dic_carga, specificityKNN_fecha_dic_carga, precisionKNN_fecha_dic_carga, 
            f1_scoreKNN_fecha_dic_carga, npvKNN_fecha_dic_carga, prevalenceKNN_fecha_dic_carga, detection_rateKNN_fecha_dic_carga, 
            balanced_accuracyKNN_fecha_dic_carga, LR_plusKNN_fecha_dic_carga, LR_minusKNN_fecha_dic_carga, AUC_KNN_fecha_dic_carga))

# Mostrar los resultados
print(metricsKNN_fecha_dic_carga)


# library(irr)
# 
# # Calcular Kappa
# kappa_KNN_fecha_dic <- kappa2(cbind(predKNN_fecha_dic, testData_fecha_dico$Y))
# 
# # Ver el valor de Kappa
# print(paste("El índice Kappa es:", round(kappa_KNN_fecha_dic$value, 3)))
# kappa_KNN_fecha_dic<-round(kappa_KNN_fecha_dic$value, 3)
```


# Modelos (con datos combat_corrected pero sin dictomizar)



```{r}
# combat_corrected_fecha_high_nodico_tot<- cbind(combat_corrected_fecha_high_tot, label=datos_filtrados$PCR.Cov)#1=neg,2=pos
combat_corrected_fecha_high_tot<-as.data.frame(combat_corrected_fecha_high_tot)
combat_corrected_fecha_high_tot$label <- as.factor(combat_corrected_fecha_high_tot$label)
```

```{r}
combat_corrected_fecha_high_nodico<-combat_corrected_fecha_high_tot[1:238,]

ciego_corrected_fecha_high_nodico<-combat_corrected_fecha_high_tot[239:327,]

```



<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- combat_corrected_fecha_high_tot<-combat_corrected_fecha_high_tot[,-ncol(combat_corrected_fecha_high_tot)] -->
<!-- combat_corrected_fecha_high_tot <- combat_corrected_fecha_high_tot %>% rename(Y = label) -->
<!-- str(combat_corrected_fecha_high$Y) -->
<!-- ``` -->



```{r}
# zero_var_indices <- nearZeroVar(combat_corrected_fecha_high)
# combat_corrected_fecha_high <- combat_corrected_fecha_high
# if (length(zero_var_indices) > 0) {
#     combat_corrected_fecha_high <- combat_corrected_fecha_high[, -zero_var_indices$Position]
# }

```


```{r}

library(tidymodels)
# set.seed asegura reproducibilidad
set.seed(42)

#Utilizo tidymodels para dividir de manera proporcional

split_data <- initial_split(combat_corrected_fecha_high_nodico, strata = "label", prop = 0.8)




# Obtener los conjuntos de entrenamiento y prueba
trainData_fecha <- training(split_data)
testData_fecha <- testing(split_data)
names(trainData_fecha)[names(trainData_fecha) == "label"] <- "Y"
names(testData_fecha)[names(testData_fecha) == "label"] <- "Y"
# Ver la distribución de clases en ambos conjuntos
table(trainData_fecha$Y)
table(testData_fecha$Y)

#trainIndex <- createDataPartition(combat_corrected_dicho[, 18], p = 0.8, list = FALSE)


# Crear conjuntos de entrenamiento y prueba, asegurando que ambos son dataframes
#trainData <- as.data.frame(combat_corrected_dicho[trainIndex, , drop = FALSE])
#testData <- as.data.frame(combat_corrected_dicho[-trainIndex, , drop = FALSE])

# Verificar los nombres de columnas (ajusta si la columna no se llama 'covid')
#colnames(trainData)

# Verificar la proporción de clases (ajusta el nombre si no es 'covid')
#table(trainData$Y)
#table(testData$Y)

```

```{r}
#set.seed(42)
library(caret)
#control1 <- trainControl(method = "cv", number = 5)
#en esta primera vez pruebo con crossval
```

```{r}
# Especificar la variable dependiente en la fórmula
formula <- Y ~ .
```



# Random forest


```{r}
grid_rf <- expand.grid(mtry = c(2, 5, 10))

# Seeds
seed.rf <- 42
set.seed(seed.rf)

seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(500, nrow(grid_rf)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# # Training control
# 
# cross_val <- trainControl(
#   method = "repeatedcv",
#   number = particiones,
#   repeats = repeticiones,
#   returnResamp = "final",
#   verboseIter = FALSE,
#   allowParallel = TRUE,
#   classProbs = TRUE,
#   seeds = seeds)
```



```{r}
trainData_fecha$Y <- factor(trainData_fecha$Y)  # Asegura que Y sea un factor
levels(trainData_fecha$Y) <- make.names(levels(trainData_fecha$Y))  # Corrige los nombres
library(caret)
RF_fecha_carga_nodic_fx <- function(df_train, model, grid, metrica = "Accuracy",  control) {

  # Entrenar el modelo
  RF_fecha <- caret::train(
    Y ~ .,
    data = df_train,
    method = model,
    tuneGrid = grid,
    metric = metrica,
    trControl = control
  )
  
  # Mostrar resumen
  print(RF_fecha)
  plot(RF_fecha)
  
  # Guardar resultado
  #save(RF_equipo, file = paste0(title, ".rda"))
  
  return(RF_fecha)
}

RF_fecha<-RF_fecha_carga_nodic_fx(df_train=trainData_fecha, model="rf", grid=grid_rf, metrica="Accuracy", control=cross_val_rf)
print(RF_fecha)
```

```{r}
RF_fecha
```

```{r}
plot(RF_fecha)
```


# ranger


```{r}
Train.rf_FECHA  <- as.data.frame(trainData_fecha) 

Test.rf_FECHA <- as.data.frame(testData_fecha)
```


```{r}
library(keras)
library(tensorflow)
library(reticulate)
library(caret)
```


```{r}

# objeto_recipe <- recipe(formula = Y ~ .,
#                         data =  Train.rf_FECHA)
# 
# objeto_recipe <- objeto_recipe %>% 
#   step_nzv(all_predictors())
# 
# trained_recipe <- prep(objeto_recipe, training = Train.rf_FECHA)
# 
# Train.rf_FECHA <- bake(trained_recipe, new_data = Train.rf_FECHA)
# Test.rf_FECHA  <- bake(trained_recipe, new_data = Test.rf_FECHA)
```



```{r}
y_train <- Train.rf_FECHA$Y
x_train <- Train.rf_FECHA[, setdiff(names(Train.rf_FECHA), "Y")]
y_test <- Test.rf_FECHA$Y
x_test <- Test.rf_FECHA[, setdiff(names(Test.rf_FECHA), "Y")]

# Crear el objeto recipe solo con las variables predictoras
objeto_recipe <- recipe(Y ~ ., data = Train.rf_FECHA)

# Preparar el objeto recipe
trained_recipe <- prep(objeto_recipe, training = Train.rf_FECHA)

# Aplicar bake solo a las variables predictoras
x_train_baked <- bake(trained_recipe, new_data = x_train)
x_test_baked <- bake(trained_recipe, new_data = x_test)

# Volver a juntar Y con los datos procesados
Train.rf_FECHA <- cbind(x_train_baked, Y = y_train)
Test.rf_FECHA <- cbind(x_test_baked, Y = y_test)

```

```{r}
# Submuestras y repeticiones

# particiones  <- 5
# repeticiones <- 15
particiones <- 3
repeticiones <- 5
```

```{r}
# Specify the tunning configuration (mtry hyperparameter depends on the number of columns)
seed.rf <- 42
set.seed(seed.rf) 


mtry <- c(1, 2, 3)
min.node.size <- seq(1, 10, 2)  # Reducir el rango
hiperparametros <- expand.grid(mtry =  mtry,
                               #min.node.size = sfecha(1, 30, 2),
                               min.node.size=min.node.size,
                               splitrule = "gini")
```


```{r}

# Seeds
seed.rf <- 42
set.seed(seed.rf)

seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(500, nrow(hiperparametros)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# # Training control
# 
# cross_val <- trainControl(
#   method = "repeatedcv",
#   number = particiones,
#   repeats = repeticiones,
#   returnResamp = "final",
#   verboseIter = FALSE,
#   allowParallel = TRUE,
#   classProbs = TRUE,
#   seeds = seeds)
# 
# # Training 
# 
# # Convertir los niveles de Train.rf$sensi a números también
# 
# # Train.rf_FECHA$Y <- factor(as.numeric(factor(Train.rf_FECHA$Y)))
# # Train.rf_FECHA$Y <- factor(Train.rf_FECHA$Y, levels = c("1", "2"))
# # levels(Train.rf_FECHA$Y) <- make.names(levels(Train.rf_FECHA$Y))

Train.rf_equipo$Y <- factor(Train.rf_equipo$Y, levels = c("Cov.Neg", "Cov.Pos"))
levels(Train.rf_equipo$Y) <- make.names(levels(Train.rf_equipo$Y))  # deja "Cov.Neg", "Cov.Pos"


```





```{r}
class(Train.rf_FECHA)
```


```{r}
Train.rf_FECHA <- as.data.frame(Train.rf_FECHA)
```


```{r}
# Primero aseguramos que Train.rf es un dataframe
Train.rf_FECHA <- as.data.frame(Train.rf_FECHA)

# Convertimos Y a factor
Train.rf_FECHA$Y <- as.factor(Train.rf_FECHA$Y)

# Definimos número de árboles
#n_trees <- 500 # default
n_trees<-200
# Establecemos semilla para reproducibilidad
set.seed(80)

# Ejecutamos el entrenamiento
results_FECHA <- caret::train(Y ~ .,
                data = Train.rf_FECHA, 
                method = "ranger",
                tuneGrid = hiperparametros,
                metric = "Accuracy",
                importance = "impurity",
                trControl = cross_val,
                num.trees = n_trees)
               #allowParallel=FALSE)  

# Vector para probar diferentes números de árboles
#num_trees_range <- c(10, 50, 100, 200, 500, 1000, 1500)

```

```{r}
# Definir los valores de num.trees a probar
num_trees_range <- c(10, 50, 100, 200, 500, 1000, 1500)

# Lista para almacenar los modelos
modelos_fecha <- list()

# Establecer semilla para reproducibilidad
set.seed(80)

# Iterar sobre cada cantidad de árboles
for (nt in num_trees_range) {
  cat("Entrenando modelo con", nt, "árboles...\n")
  
  modelos_fecha[[as.character(nt)]] <- caret::train(
    Y ~ .,
    data = Train.rf_FECHA,
    method = "ranger",
    tuneGrid = hiperparametros,
    metric = "Accuracy",
    importance = "impurity",
    trControl = cross_val,
    num.trees = nt
  )
}


```





```{r}
  resultados_modelos <- data.frame(
  num_trees = num_trees_range,
  Accuracy = sapply(modelos_fecha, function(m) max(m$results$Accuracy, na.rm = TRUE)),
  Kappa = sapply(modelos_fecha, function(m) max(m$results$Kappa, na.rm = TRUE)),
  mtry = sapply(modelos_fecha, function(m) m$bestTune$mtry),
  min.node.size = sapply(modelos_fecha, function(m) m$bestTune$min.node.size)
)

# Ordenamos los modelos de mejor a peor Accuracy
resultados_modelos <- resultados_modelos[order(-resultados_modelos$Accuracy), ]

print(head(resultados_modelos, 20)) 

```


```{r}
# Encontrar el índice del modelo con mejor Accuracy en la tabla de resultados
mejor_idx <- which.max(resultados_modelos$Accuracy)

# Extraer la mejor combinación de hiperparámetros
mejor_num_trees <- resultados_modelos$num_trees[mejor_idx]
mejor_mtry <- resultados_modelos$mtry[mejor_idx]
mejor_min_node_size <- resultados_modelos$min.node.size[mejor_idx]

# Extraer el modelo correspondiente en la lista
mejor_modelo <- modelos_fecha_dico[[as.character(mejor_num_trees)]]

# Mostrar los hiperparámetros seleccionados
cat("Mejor modelo seleccionado:\n")
cat("Número de árboles:", mejor_num_trees, "\n")
cat("mtry:", mejor_mtry, "\n")
cat("min.node.size:", mejor_min_node_size, "\n")

# Mostrar detalles del mejor modelo
print(mejor_modelo)

```

```{r}
# ranger_fecha <- caret::train(
#   Y ~ .,
#   data = Train.rf_fecha_dico, 
#   method = "ranger",
#   tuneGrid = data.frame(mtry = 1, min.node.size = 7, splitrule = "gini"), 
#   metric = "Accuracy",
#   importance = "impurity",
#   trControl = cross_val,  # Si querés usar validación cruzada
#   num.trees = 50  # Número de árboles fijo
# )
# print(ranger_fecha_dico)
ranger_fecha_matrix_nodic_fx<-function(df_train, model, grid, metrica,  num.trees){

ranger_fecha <- caret::train(
  Y ~ .,
  data = df_train,
  method = "ranger",
  tuneGrid = grid,
  metric = "Accuracy",
  importance = "impurity",
  trControl = cross_val_ranger,  # Si querés usar validación cruzada
  num.trees=num.trees  # Número de árboles fijo
)

return(ranger_fecha)
}

#

ranger_fecha<-ranger_fecha_matrix_nodic_fx(Train.rf_fecha_dico,"ranger",hiperparametros,"Accuracy", num.trees=mejor_num_trees)
```


```{r}
Test.rf_FECHA$Y<-as.factor(Test.rf_FECHA$Y)
str(Test.rf_FECHA$Y)
```

```{r}
testRF_NOID_FECHA <- Test.rf_FECHA[, -which(names(Test.rf_FECHA) == "Y")]

```



```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predRANGER_FECHA_carga<-predict(ranger_fecha, newdata = testRF_NOID_FECHA)#matriz binarizada
print(predRANGER_FECHA_carga)

predRANGER_FECHA_carga <- factor(as.character(predRANGER_FECHA_carga), 
                             levels = c("X1", "X2"),
                             labels = c("1", "2"))
predRANGER_FECHA_carga <- factor(predRANGER_FECHA_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))

# Obtener las etiquetas reales del conjunto de datos de prueba
y_test <- Test.rf_FECHA$Y

prob_predRanger_FECHA <- predict(ranger_fecha, newdata = testRF_NOID_FECHA, type = "prob")

colnames(prob_predRanger_FECHA)
y_test <- Test.rf_FECHA$Y
# Asegúrate de que y_test sea un factor con los niveles correctos
#y_test <- factor(Test.rf_FECHA$Y, levels = c(1, 2), labels = c("Cov.Neg", "Cov.Pos"))


Ranger_metrics_fecha_carga <- caret::confusionMatrix(predRANGER_FECHA_carga, y_test, positive = "Cov.Pos")

```



```{r}
library(pROC)

# Asegúrate de que y_test sea numérico y esté alineado con los niveles 1 y 2
y_test_numeric <- as.numeric(y_test)

roc_curve <- roc(response = y_test_numeric, 
                 predictor = prob_predRanger_FECHA[, "X2"], 
                 levels = c(1, 2))
AUC_Ranger_FECHA_carga <- auc(roc_curve)
print(paste("El valor de AUC es:", round(AUC_Ranger_FECHA_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve, main = "Curva ROC", col = "blue", lwd = 2)
# 
# confusion_matrixRANGER <- table(predRANGER_FECHA, y_test)
# # Imprimir la matriz de confusión
# print(confusion_matrixRANGER)
```


```{r}
# Carga los paquetes necesarios
library(caret)
accuracyRanger_FECHA_carga <- Ranger_metrics_fecha_carga$overall["Accuracy"]
kappaRanger_FECHA_carga <- Ranger_metrics_fecha_carga$overall["Kappa"]
# Métricas por clase
sensitivityRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Sensitivity"]
specificityRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Specificity"]
precisionRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Pos Pred Value"]
recallRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["F1"]
npvRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Neg Pred Value"]
prevalenceRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Prevalence"]
detection_rateRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Detection Rate"]
balanced_accuracyRanger_FECHA_carga <- Ranger_metrics_fecha_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusRanger_FECHA_carga <- sensitivityRanger_FECHA_carga / (1 - specificityRanger_FECHA_carga)
LR_minusRanger_FECHA_carga <- (1 - sensitivityRanger_FECHA_carga) / specificityRanger_FECHA_carga

# Para manejar valores especiales
LR_plusRanger_FECHA_carga <- ifelse(is.nan(LR_plusRanger_FECHA_carga) | is.infinite(LR_plusRanger_FECHA_carga), NA, LR_plusRanger_FECHA_carga)
LR_minusRanger_FECHA_carga <- ifelse(is.nan(LR_minusRanger_FECHA_carga) | is.infinite(LR_minusRanger_FECHA_carga), NA, LR_minusRanger_FECHA_carga)

# Crear un dataframe con todas las métricas
metricsRanger_FECHA_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  Ranger_FECHA_carga = c(accuracyRanger_FECHA_carga, kappaRanger_FECHA_carga, sensitivityRanger_FECHA_carga, specificityRanger_FECHA_carga, precisionRanger_FECHA_carga, 
            f1_scoreRanger_FECHA_carga, npvRanger_FECHA_carga, prevalenceRanger_FECHA_carga, detection_rateRanger_FECHA_carga, 
            balanced_accuracyRanger_FECHA_carga, LR_plusRanger_FECHA_carga, LR_minusRanger_FECHA_carga, AUC_Ranger_FECHA_carga))

# Mostrar los resultados
print(metricsRanger_FECHA_carga)

# # Precisión (Accuracy)
# accuracy_RANGER_fecha <- sum(diag(confusion_matrixRANGER)) / sum(confusion_matrixRANGER)
# print(paste("La precisión (Accuracy) es:", round(accuracy_RANGER_fecha,2)))
# 
# # Sensibilidad (Recall o TPR)
# sensitivity_RANGER_fecha <- confusion_matrixRANGER[2, 2] / sum(confusion_matrixRANGER[, 2])
# print(paste("La sensibilidad es:", round(sensitivity_RANGER_fecha,2)))
# 
# # Especificidad (TNR)
# specificity_RANGER_fecha <- confusion_matrixRANGER[1, 1] / sum(confusion_matrixRANGER[, 1])
# print(paste("la especificidad es:", round(specificity_RANGER_fecha,2)))
# 
# # Valor Predictivo Positivo (PPV o Precision)
# ppv_RANGER_fecha<- confusion_matrixRANGER[2, 2] / sum(confusion_matrixRANGER[2, ])
# print(paste("el VPP es:", round(ppv_RANGER_fecha,2)))
# 
# # Valor Predictivo Negativo (VPN)
# npv_RANGER_fecha<- confusion_matrixRANGER[1, 1] / sum(confusion_matrixRANGER[1, ])
# print(paste("el VPN es: ",  round(npv_RANGER_fecha,2)))


```





# KNN


```{r}
tuneGrid <- expand.grid(k = 1:15)
# Seeds
seed.rf <- 42
set.seed(seed.rf)

seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(500, nrow(tuneGrid)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# # Training control
# 
# cross_val <- trainControl(
#   method = "repeatedcv",
#   number = particiones,
#   repeats = repeticiones,
#   returnResamp = "final",
#   verboseIter = FALSE,
#   allowParallel = TRUE,
#   classProbs = TRUE,
#   seeds = seeds)
```


```{r}

# KNN_fecha <- caret::train(formula, 
#                     data = trainData_fecha, 
#                     trControl = cross_val, 
#                     method = "knn", 
#                     metric = "Accuracy", 
#                     preProcess = c("center","scale"),
#                     tuneGrid = tuneGrid)
# 
# KNN_fecha
KNN_fecha_matrix_nodic_fx <- function(df_train, model, grid, metrica = "Accuracy",  control, preProcess) {
 KNN_fecha <- caret::train(
    Y ~ .,
    data = df_train,
    method = model,
    tuneGrid = grid,
    metric = metrica,
    trControl = cross_val_knn,
    preProcess = preProcess
  )
  
  # Mostrar resumen
  print(KNN_fecha)
  plot(KNN_fecha)
  
  # Guardar resultado
  #save(KNN_fecha_tot_fx, file = paste0(title, ".rda"))
  
  return(KNN_fecha)
}

KNN_fecha<-KNN_fecha_matrix_nodic_fx(df_train=trainData_fecha, model="knn", grid=tuneGrid, metrica="Accuracy",  preProcess = c("center","scale") )
print(KNN_fecha)
```

```{r}
plot(KNN_fecha)
```

# GLMNET


```{r}

tuneGrid <- expand.grid(
  alpha = seq(0, 1, by = 0.1),  # From 0 (Ridge) to 1 (Lasso)
  lambda = 10^seq(-3, 3, length = 100)  # Logarithmic scale for lambda
)
# Seeds
seed.rf <- 42
set.seed(seed.rf)
max_sample <- max(500, nrow(tuneGrid) * 2)
seeds <- vector(mode = "list", length = (particiones * repeticiones) + 1)

for (i in 1:(particiones * repeticiones)) {
  seeds[[i]] <- sample.int(max_sample, nrow(tuneGrid)) 
}

seeds[[(particiones * repeticiones) + 1]] <- sample.int(500, 1)

# Training control
```



```{r}
# # Training control
# 
# cross_val <- trainControl(
#   method = "repeatedcv",
#   number = particiones,
#   repeats = repeticiones,
#   returnResamp = "final",
#   verboseIter = FALSE,
#   allowParallel = TRUE,
#   classProbs = TRUE,
#   seeds = seeds)
```


```{r}

# #set.seed(42)
# GLM_fecha <- caret::train(formula, 
#                   data = trainData_fecha,  
#                    method = "glmnet",
#                    metric = "Accuracy",
#                    tuneLength = 3,
#                    trControl = cross_val,
#                   tuneGrid=tuneGrid)
# 
# GLM_fecha 
GLM_fecha_matrix_nodic_fx <- function(df_train, model, grid, metrica = "Accuracy", control) {

  
  # Entrenar el modelo
  GLM_fecha <- caret::train(
    Y ~ .,
    data = df_train,
    method = model,
    tuneGrid = grid,
    metric = metrica,
    trControl = control
  )
  
  # Mostrar resumen
  print(GLM_fecha)
  plot(GLM_fecha, main = title)
  
  # Guardar resultado
  #save(GLM_fecha_tot, file = paste0(title, ".rda"))
  
  return(GLM_fecha)
}

GLM_fecha<-GLM_fecha_matrix_nodic_fx(df_train=trainData_fecha, model="glmnet", grid=tuneGrid, metrica="Accuracy", control=cross_val_glm)
print(GLM_fecha)
```

```{r}
# Imprimir los mejores hiperparámetros
best_params <- GLM_fecha$bestTune
print("Best Hyperparameters:")
print(best_params)

# Extraer accuracy y kappa del mejor modelo
# Buscamos la fila que corresponde a los mejores hiperparámetros en el data frame model$results
best_model_index <- apply(GLM_fecha$results, 1, function(row) {
  all(row[1:length(best_params)] == as.numeric(best_params))
})

best_model_results <- GLM_fecha$results[best_model_index, ]



# Imprimir accuracy y kappa del mejor modelo
accuracy <- best_model_results$Accuracy
kappa <- best_model_results$Kappa

print("Accuracy of the Best Model:")
print(accuracy)

print("Kappa of the Best Model:")
print(kappa)

```

# Prediccion

```{r}
testData_fecha$Y<-as.factor(testData_fecha$Y)
str(testData_fecha$Y)
```

```{r}
testData_NOID_fecha <- testData_fecha[, -which(names(testData_fecha) == "Y")]

```

# RF

```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predRF_fecha_carga<-predict(RF_fecha, newdata = testData_NOID_fecha)#matriz binarizada
print(predRF_fecha_carga)

# predRF_fecha_carga <- factor(as.character(predRF_fecha_carga), 
#                              levels = c("X1", "X2"),
#                              labels = c("1", "2"))
# predRF_fecha_carga <- factor(predRF_fecha_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))

# Obtener las etiquetas reales del conjunto de datos de prueba
y_test <- testData_fecha$Y
#y_testDIC <- FeatureMatrix_Dic_df$Y#Matriz binarizada
#y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))

```

```{r}
# confusion_matrixRF <- table(predRF_fecha, y_test)
# Imprimir la matriz de confusión
# print(confusion_matrixRF)
RF_metrics_fecha_carga <- caret::confusionMatrix(predRF_fecha_carga, y_test, positive = "Cov.Pos")


```

```{r}
# Precisión (Accuracy)
# accuracy_RF_fecha <- sum(diag(confusion_matrixRF)) / sum(confusion_matrixRF)
# print(paste("La precisión (Accuracy) es:", round(accuracy_RF_fecha,2)))
# 
# # Sensibilidad (Recall o TPR)
# sensitivity_RF_fecha <- confusion_matrixRF[2, 2] / sum(confusion_matrixRF[, 2])
# print(paste("La sensibilidad es:", round(sensitivity_RF_fecha,2)))
# 
# # Especificidad (TNR)
# specificityRF_fecha <- confusion_matrixRF[1, 1] / sum(confusion_matrixRF[, 1])
# print(paste("la especificidad es:", round(specificityRF_fecha,2)))
# 
# # Valor Predictivo Positivo (PPV o Precision)
# ppv_RF_fecha <- confusion_matrixRF[2, 2] / sum(confusion_matrixRF[2, ])
# print(paste("el VPP es:", round(ppv_RF_fecha,2)))
# 
# # Valor Predictivo Negativo (VPN)
# npv_RF_fecha <- confusion_matrixRF[1, 1] / sum(confusion_matrixRF[1, ])
# print(paste("el VPN es: ",  round(npv_RF_fecha,2)))


library(pROC)

prob_predRF_fecha <- predict(RF_fecha, newdata = testData_NOID_fecha, type = "prob")

# Asegúrate de que y_test sea numérico y esté alineado con los niveles 1 y 2
y_test_numeric <- as.numeric(y_test)

roc_curve <- roc(response = y_test_numeric, predictor = prob_predRF_fecha[, "Cov.Pos"], levels = c(1, 2))
AUC_RF_fecha_carga <- auc(roc_curve)

print(paste("El valor de AUC es:", round(AUC_RF_fecha_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve, main = "Curva ROC", col = "blue", lwd = 2)

```


```{r}
library(caret)
accuracyRF_fecha_carga <- RF_metrics_fecha_carga$overall["Accuracy"]
kappaRF_fecha_carga <- RF_metrics_fecha_carga$overall["Kappa"]
# Métricas por clase
sensitivityRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Sensitivity"]
specificityRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Specificity"]
precisionRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Pos Pred Value"]
recallRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreRF_fecha_carga <- RF_metrics_fecha_carga$byClass["F1"]
npvRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Neg Pred Value"]
prevalenceRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Prevalence"]
detection_rateRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Detection Rate"]
balanced_accuracyRF_fecha_carga <- RF_metrics_fecha_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusRF_fecha_carga <- sensitivityRF_fecha_carga / (1 - specificityRF_fecha_carga)
LR_minusRF_fecha_carga <- (1 - sensitivityRF_fecha_carga) / specificityRF_fecha_carga

# Para manejar valores especiales
LR_plusRF_fecha_carga <- ifelse(is.nan(LR_plusRF_fecha_carga) | is.infinite(LR_plusRF_fecha_carga), NA, LR_plusRF_fecha_carga)
LR_minusRF_fecha_carga <- ifelse(is.nan(LR_minusRF_fecha_carga) | is.infinite(LR_minusRF_fecha_carga), NA, LR_minusRF_fecha_carga)

# Crear un dataframe con todas las métricas
metricsRF_fecha_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  RF_fecha_carga = c(accuracyRF_fecha_carga, kappaRF_fecha_carga, sensitivityRF_fecha_carga, specificityRF_fecha_carga, precisionRF_fecha_carga, f1_scoreRF_fecha_carga, npvRF_fecha_carga, prevalenceRF_fecha_carga, detection_rateRF_fecha_carga, 
            balanced_accuracyRF_fecha_carga, LR_plusRF_fecha_carga, LR_minusRF_fecha_carga, AUC_RF_fecha_carga))

# Mostrar los resultados
print(metricsRF_fecha_carga)


# library(irr)

# Calcular Kappa
# kappa_RFfecha <- kappa2(cbind(predRF_fecha, testData_fecha$Y))
# 
# # Ver el valor de Kappa
# print(paste("El índice Kappa es:", round(kappa_RFfecha$value, 3)))
# kappa_RFfecha<-round(kappa_RFfecha$value, 3)
```


# Prediccion KNN

```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predKNN_fecha_carga<-predict(KNN_fecha, newdata = testData_NOID_fecha)#matriz binarizada
print(predKNN_fecha_carga)
# predKNN_fecha_carga <- factor(as.character(predKNN_fecha_carga), 
#                              levels = c("X1", "X2"),
#                              labels = c("1", "2"))
# predKNN_fecha_carga <- factor(predKNN_fecha_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))



# Obtener las etiquetas reales del conjunto de datos de prueba
y_test <- testData_fecha$Y
#y_testDIC <- FeatureMatrix_Dic_df$Y#Matriz binarizada
#y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))
```

```{r}
# confusion_matrixKNN <- table(predKNN_fecha, y_test)
# Imprimir la matriz de confusión
# print(confusion_matrixKNN)
KNN_metrics_fecha_carga <- caret::confusionMatrix(predKNN_fecha_carga, y_test, positive = "Cov.Pos")
```

```{r}
# #metricas
# # Precisión
# accuracy_KNN_fecha <- sum(diag(confusion_matrixKNN)) / sum(confusion_matrixKNN)
# print(accuracy_KNN_fecha)
# # Precisión positiva (VP) o sensibilidad
# sensitivity_KNN_fecha<- confusion_matrixKNN[2, 2] / sum(confusion_matrixKNN[,2 ])
# print(sensitivity_KNN_fecha)
# # Precisión negativa (VN) o especificidad
# specificity_KNN_fecha <- confusion_matrixKNN[1, 1] / sum(confusion_matrixKNN[,1 ])
# specificity_KNN_fecha
# 
# # Valor predictivo positivo (VPP)
# ppv_KNN_fecha <- confusion_matrixKNN[2, 2] / sum(confusion_matrixKNN[2, ])
# print(ppv_KNN_fecha)
# # Valor predictivo negativo (VPN)
# npv_KNN_fecha <- confusion_matrixKNN[1, 1] / sum(confusion_matrixKNN[1, ])
# print(npv_KNN_fecha)


prob_predKNNfecha <- predict(KNN_fecha, newdata = testData_NOID_fecha, type = "prob")

# Verifica los nombres de las columnas (clases)
print(colnames(prob_predKNNfecha))  # Deberían ser "1" y "2" o los nombres de las clases

# Asegúrate de que y_test sea numérico con niveles 1 y 2
y_test_numeric <- as.numeric(testData_fecha$Y)

# Calcula la curva ROC usando la probabilidad de la clase positiva ("2")
roc_curve_knn <- roc(response = y_test_numeric, predictor = prob_predKNNfecha[, "Cov.Pos"], levels = c(1, 2))

# Calcula el AUC
AUC_KNN_fecha_carga <- auc(roc_curve_knn)
print(paste("El valor de AUC es:", round(AUC_KNN_fecha_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve_knn, main = "Curva ROC - KNN", col = "blue", lwd = 2)
```



```{r}
library(caret)
accuracyKNN_fecha_carga <- KNN_metrics_fecha_carga$overall["Accuracy"]
kappaKNN_fecha_carga<- KNN_metrics_fecha_carga$overall["Kappa"]
# Métricas por clase
sensitivityKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Sensitivity"]
specificityKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Specificity"]
precisionKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Pos Pred Value"]
recallKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["F1"]
npvKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Neg Pred Value"]
prevalenceKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Prevalence"]
detection_rateKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Detection Rate"]
balanced_accuracyKNN_fecha_carga <- KNN_metrics_fecha_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusKNN_fecha_carga <- sensitivityKNN_fecha_carga / (1 - specificityKNN_fecha_carga)
LR_minusKNN_fecha_carga <- (1 - sensitivityKNN_fecha_carga) / specificityKNN_fecha_carga

# Para manejar valores especiales
LR_plusKNN_fecha_carga <- ifelse(is.nan(LR_plusKNN_fecha_carga) | is.infinite(LR_plusKNN_fecha_carga), NA, LR_plusKNN_fecha_carga)
LR_minusKNN_fecha_carga <- ifelse(is.nan(LR_minusKNN_fecha_carga) | is.infinite(LR_minusKNN_fecha_carga), NA, LR_minusKNN_fecha_carga)

# Crear un dataframe con todas las métricas
metricsKNN_fecha_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  KNN_fecha_carga = c(accuracyKNN_fecha_carga, kappaKNN_fecha_carga, sensitivityKNN_fecha_carga, specificityKNN_fecha_carga, precisionKNN_fecha_carga, 
            f1_scoreKNN_fecha_carga, npvKNN_fecha_carga, prevalenceKNN_fecha_carga, detection_rateKNN_fecha_carga, 
            balanced_accuracyKNN_fecha_carga, LR_plusKNN_fecha_carga, LR_minusKNN_fecha_carga, AUC_KNN_fecha_carga))

# Mostrar los resultados
print(metricsKNN_fecha_carga)

# library(irr)
# 
# # Calcular Kappa
# kappa_KNNfecha <- kappa2(cbind(predKNN_fecha, testData_fecha$Y))
# 
# # Ver el valor de Kappa
# print(paste("El índice Kappa es:", round(kappa_KNNfecha$value, 3)))
# kappa_KNNfecha<-round(kappa_KNNfecha$value, 3)
```




```{r}
#prediccionesRF1<-predict(resultadosRF, newdata = dataNOID_test)
predGLM_fecha_carga<-predict(GLM_fecha, newdata = testData_NOID_fecha)#matriz binarizada
print(predGLM_fecha_carga)

# predGLM_fecha_carga <- factor(as.character(predGLM_fecha_carga), 
#                              levels = c("X1", "X2"),
#                              labels = c("1", "2"))
#predGLM_fecha_carga <- factor(predGLM_fecha_carga, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))


# Obtener las etiquetas reales del conjunto de datos de prueba
y_test <- testData_fecha$Y
#y_testDIC <- FeatureMatrix_Dic_df$Y#Matriz binarizada
#y_test <- factor(y_test, levels = c("1", "2"), labels = c("Cov.Neg", "Cov.Pos"))
```

```{r}
GLM_metrics_fecha_carga <- caret::confusionMatrix(predGLM_fecha_carga, y_test, positive = "Cov.Pos")
```


```{r}
# # Precisión (Accuracy)
# accuracy_GLM_fecha <- sum(diag(confusion_matrixGLM)) / sum(confusion_matrixGLM)
# print(paste("La precisión (Accuracy) es:", round(accuracy_GLM_fecha,2)))
# 
# # Sensibilidad (Recall o TPR)
# sensitivity_GLM_fecha <- confusion_matrixGLM[2, 2] / sum(confusion_matrixGLM[, 2])
# print(paste("La sensibilidad es:", round(sensitivity_GLM_fecha,2)))
# 
# # Especificidad (TNR)
# specificity_GLM_fecha <- confusion_matrixGLM[1, 1] / sum(confusion_matrixGLM[, 1])
# print(paste("la especificidad es:", round(specificity_GLM_fecha,2)))
# 
# # Valor Predictivo Positivo (PPV o Precision)
# ppv_GLM_fecha <- confusion_matrixGLM[2, 2] / sum(confusion_matrixGLM[2, ])
# print(paste("el VPP es:", round(ppv_GLM_fecha,2)))
# 
# # Valor Predictivo Negativo (VPN)
# npv_GLM_fecha <- confusion_matrixGLM[1, 1] / sum(confusion_matrixGLM[1, ])
# print(paste("el VPN es: ",  round(npv_GLM_fecha,2)))




# Predicciones probabilísticas con el modelo GLM
prob_predGLM_fecha <- predict(GLM_fecha, newdata = testData_NOID_fecha, type = "prob")

# Verifica los nombres de las columnas (clases)
print(colnames(prob_predGLM_fecha))  # Deberían ser "1" y "2" o los nombres de las clases

# Asegúrate de que y_test sea numérico con niveles 1 y 2
y_test_numeric <- as.numeric(testData_fecha$Y)

# Calcula la curva ROC usando la probabilidad de la clase positiva ("2")
roc_curve_glm <- roc(response = y_test_numeric, predictor = prob_predGLM_fecha[, "Cov.Pos"], levels = c(1, 2))

# Calcula el AUC
AUC_GLM_fecha_carga <- auc(roc_curve_glm)
print(paste("El valor de AUC es:", round(AUC_GLM_fecha_carga, 3)))

# Visualiza la curva ROC
plot(roc_curve_glm, main = "Curva ROC - GLM", col = "red", lwd = 2)
```

```{r}
# Carga los paquetes necesarios
library(caret)
accuracyGLM_fecha_carga <- GLM_metrics_fecha_carga$overall["Accuracy"]
kappaGLM_fecha_carga <- GLM_metrics_fecha_carga$overall["Kappa"]
# Métricas por clase
sensitivityGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Sensitivity"]
specificityGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Specificity"]
precisionGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Pos Pred Value"]
recallGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Sensitivity"]  # Igual a sensitivity
f1_scoreGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["F1"]
npvGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Neg Pred Value"]
prevalenceGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Prevalence"]
detection_rateGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Detection Rate"]
balanced_accuracyGLM_fecha_carga <- GLM_metrics_fecha_carga$byClass["Balanced Accuracy"]

# Calcular LR+ y LR- que no vienen directamente en confusionMatrix
LR_plusGLM_fecha_carga <- sensitivityGLM_fecha_carga / (1 - specificityGLM_fecha_carga)
LR_minusGLM_fecha_carga <- (1 - sensitivityGLM_fecha_carga) / specificityGLM_fecha_carga

# Para manejar valores especiales
LR_plusGLM_fecha_carga <- ifelse(is.nan(LR_plusGLM_fecha_carga) | is.infinite(LR_plusGLM_fecha_carga), NA, LR_plusGLM_fecha_carga)
LR_minusGLM_fecha_carga <- ifelse(is.nan(LR_minusGLM_fecha_carga) | is.infinite(LR_minusGLM_fecha_carga), NA, LR_minusGLM_fecha_carga)

# Crear un dataframe con todas las métricas
metricsGLM_fecha_carga <- data.frame(
  Metric = c("Accuracy", "Kappa", "Sensitivity", "Specificity", "Precision", 
             "F1_Score", "NPV", "Prevalence", "Detection_Rate", 
             "Balanced_Accuracy", "LR+", "LR-", "AUC"),
  GLM_fecha_carga = c(accuracyGLM_fecha_carga, kappaGLM_fecha_carga, sensitivityGLM_fecha_carga, specificityGLM_fecha_carga, precisionGLM_fecha_carga, 
            f1_scoreGLM_fecha_carga, npvGLM_fecha_carga, prevalenceGLM_fecha_carga, detection_rateGLM_fecha_carga, 
            balanced_accuracyGLM_fecha_carga, LR_plusGLM_fecha_carga, LR_minusGLM_fecha_carga, AUC_GLM_fecha_carga))

# Mostrar los resultados
print(metricsGLM_fecha_carga)


# library(irr)

# # Calcular Kappa
# kappa_GLM_fecha <- kappa2(cbind(predGLM_fecha, testData_fecha$Y))
# 
# # Ver el valor de Kappa
# print(paste("El índice Kappa es:", round(kappa_GLM_fecha$value, 3)))
# kappa_GLM_fecha<-round(kappa_GLM_fecha$value, 3)
```

# COMPARACION MODELOS COMBAT FECHA

```{r}
# resultados_modelos_fecha <- data.frame(
#   Modelo = c("RF_fechadic", "GLMC_fechadic", "KNN_fechadic", "Ranger_fechadic",  "RF_fecha", "GLM_fecha", "KNN_fecha", "Ranger_fecha"),
#   Accuracy = c(accuracyRF_fecha_dic, accuracy_GLM_fecha_dic , accuracy_KNN_fecha_dic, accuracy_RANGER_fecha_dic, accuracy_RF_fecha, accuracy_GLM_fecha , accuracy_KNN_fecha, accuracy_RANGER_fecha),
#   Sensibilidad=c(sensitivityRF_fecha_dic, sensitivity_GLM_fecha_dic, sensitivity_KNN_fecha_dic, sensitivity_RANGER_fecha_dic, sensitivity_RF_fecha, sensitivity_GLM_fecha, sensitivity_KNN_fecha, sensitivity_RANGER_fecha),
#   Especificidad = c(specificityRF_fecha_dic, specificity_GLM_fecha_dic, specificity_KNN_fecha_dic, specificity_RANGER_fecha_dic, specificityRF_fecha, specificity_GLM_fecha, specificity_KNN_fecha, specificity_RANGER_fecha),
#   AUC= c(AUC_RF_fecha_dic, AUC_GLM_fecha_dic, AUC_KNN_fecha, AUC_Ranger_FECHA_dich, AUC_RF_fecha, AUC_GLM_fecha, AUC_KNN_fecha, AUC_Ranger_FECHA),
# kappa= c(kappa_RFfecha_dic, kappa_GLM_fecha_dic, kappa_KNN_fecha_dic, kappa_RANGERfecha_dic, kappa_RFfecha, kappa_GLM_fecha, kappa_KNNfecha, kappa_RANGERfecha))
# 
# 
# print(resultados_modelos_fecha)

```




```{r}


# Cargar la librería
# library(writexl)

# Exportar a Excel
# write_xlsx(resultados_modelos_fecha, "C:/Users/karin/Desktop/MCD/TESIS/resultados_modelos_fecha.xlsx")
```



